from handbook_lib import render


def _pack(cat, tech, rows):
    out = []
    lang = {
        "linux": "bash", "git": "bash", "bash": "bash", "sql": "sql",
        "docker": "dockerfile", "databases": "sql", "networking": "text",
        "protocols": "text", "microcontrollers": "c", "electronics": "text",
        "robotics": "text", "software-architecture": "text", "app": "text",
    }[cat]
    for i, row in enumerate(rows, 1):
        slug, title, section, desc, about, robot, code, mistakes, canvas, related = row
        out.append(render(
            cat=cat, slug=slug, title=title, section=section, order=i,
            description=desc, tags=[cat, section.lower()], technologies=[tech],
            related=related, about=about, robot=robot, lang=lang,
            code=code, mistakes=mistakes, canvas=canvas,
        ))
    return out


def linux_articles():
    return _pack("linux", "Linux", [
        ("intro", "Linux на роботе", "Основы", "Зачем Linux на SBC и IPC.",
         "Linux — ОС SBC и промышленных ПК: сеть, файлы, процессы, контейнеры. Это не RTOS. Жёсткий 1 кГц лучше на MCU.",
         "Raspberry Pi / IPC крутит шлюз, SLAM, UI. STM32 крутит PWM. Граница — UART/CAN.",
         "uname -a\ncat /etc/os-release",
         ["ждать от Pi PREEMT_RT без настройки и измерения", "root для всего сервиса"],
         "Блок SBC: ОС в Hardware Data. Алгоритмы Linux-сервисов — отдельные software-блоки.",
         ["linux-fs", "linux-systemd", "linux-realtime"]),
        ("fs", "Файловая система и пути", "Основы", "FHS, /etc, /var, /dev.",
         "/dev — устройства, /etc — конфиги, /var/lib — состояние, /opt или /usr/local — сервисы.",
         "Калибровка в /var/lib/robot, unit в /etc/systemd/system, UART /dev/ttyACM0.",
         "ls /dev/ttyACM* /dev/ttyUSB* /dev/can*",
         ["хранить конфиг в домашней папке pi и запускать из systemd без User=", "относительные пути"],
         "Документация Linux-компонента: абсолютные пути артефактов.",
         ["linux-permissions", "linux-udev", "python-files"]),
        ("permissions", "Права, пользователи, groups", "Основы", "dialout, gpio, не всё от root.",
         "Сервис робота — отдельный user в группах dialout/i2c/gpio. Root скрывает ошибки прав до продакшена.",
         "Пользователь robot читает ttyACM0. Прошивка через systemd-сервис с DeviceAllow.",
         "id robot\nls -l /dev/ttyACM0",
         ["chmod 777 на /dev", "пароль pi/raspberry в изделии"],
         "В notes SBC: user сервиса и группы. Это требование безопасности.",
         ["linux-udev", "linux-systemd", "linux-ssh"]),
        ("udev", "udev и стабильные имена", "Устройства", "Не /dev/ttyUSB0 «какой сегодня».",
         "Правила udev по idVendor/idProduct/serial дают /dev/imu и /dev/lidar.",
         "Два USB-serial: IMU и MCU. Без udev после перетыкания порты меняются — ложный протокол.",
         "SUBSYSTEM==\"tty\", ATTRS{serial}==\"ABC\", SYMLINK+=\"robot-mcu\"",
         ["правило по номеру порта USB-хаба", "не перезагрузить udev после деплоя"],
         "Имена устройств — в документации связей UART. Hardware notes камеры/IMU.",
         ["linux-fs", "linux-permissions", "python-serial"]),
        ("processes", "Процессы, сигналы, nice", "Процессы", "ps, top, SIGTERM.",
         "Сервис должен корректно гасить PWM-уставки на SIGTERM (systemd stop), не только kill -9.",
         "Перед обновлением: stop сервиса → безопасный coast → flash.",
         "ps aux | grep robot\nkill -TERM $(pidof robot-svc)",
         ["kill -9 как обычный рестарт", "зомби-процессы драйвера камеры, держащие /dev/video0"],
         "Алгоритм shutdown компонента API/Supervisor.",
         ["linux-systemd", "linux-journalctl", "python-signals"]),
        ("systemd", "systemd unit", "Процессы", "Автозапуск шлюза.",
         "Restart=on-failure, WatchdogSec, After=network-online, User=robot, SupplementaryGroups=dialout.",
         "Робот включили — шлюз поднялся, MQTT last will сработал при падении.",
         "[Service]\nExecStart=/usr/bin/robot-svc\nRestart=on-failure",
         ["Restart=always без backoff при Hardware Fault", "WorkingDirectory не задан"],
         "Запуск — README блока SBC/Backend. Связь с MQTT брокером: After=mosquitto.",
         ["linux-journalctl", "linux-processes", "docker-compose"]),
        ("journalctl", "journalctl и логи", "Наблюдаемость", "Как читать службу.",
         "Логи службы: journalctl -u robot-svc -f. Уровни как в logging Python.",
         "После FAULT сначала журнал, потом осциллограф. Иначе потеряете последовательность.",
         "journalctl -u robot-svc --since '10 min ago'",
         ["логировать в файл в /tmp и терять после ребута без причины", "без RateLimit понимание флуда IMU"],
         "Наблюдаемость: куда пишем. Документ компонента + связь с UI логов, если есть.",
         ["linux-systemd", "python-logging", "cpp-logging"]),
        ("ssh", "SSH и доступ к изделию", "Сеть ОС", "Ключи, не пароль в цехе.",
         "Только ключи, отдельный user, порт не обязательно 22 в публичной сети. Tunnel для MQTT отладки.",
         "Инженер настраивает робота в поле. Пароль raspberry — инцидент.",
         "ssh -i robot.ed25519 robot@10.0.0.21",
         ["permit root login", "общий ключ на 40 роботов без учёта"],
         "Доступ — вложенный холст операций, не runtime-архитектура, но требование безопасности.",
         ["linux-permissions", "linux-firewall", "networking-vpn"]),
        ("net-tools", "ip, ss, ping, tcpdump", "Сеть ОС", "Диагностика Ethernet/Wi-Fi.",
         "Сначала L3: ping, ip addr. Потом сокеты ss -l. Потом tcpdump порта MQTT 1883.",
         "Робот «не видит» брокер: это DNS, маршрут, firewall или брокер down — не «Python сломался».",
         "ss -lntp | grep 1883\nip route",
         ["сразу переписывать код сервиса", "tcpdump без фильтра на 1 Гбит камере"],
         "Связь Ethernet/Wi-Fi на холсте. Troubleshooting — в docs шлюза.",
         ["networking-ip", "linux-firewall", "protocols-mqtt"]),
        ("firewall", "nftables/iptables кратко", "Сеть ОС", "Минимальная экспозиция.",
         "На изделии открыты только SSH (ограниченно), MQTT если нужно, API. Не все порты Docker.",
         "Операторская сеть vs OT. Робот не торчит Node-RED в интернет.",
         "nft add rule inet filter input tcp dport 1883 ip saddr 10.0.0.0/24 accept",
         ["disable firewall «чтобы заработало» навсегда", "проброс 0.0.0.0:80"],
         "Требования безопасности на блок External Access.",
         ["linux-ssh", "docker-networks", "networking-nat"]),
        ("disks", "Диски, overlay, износ SD", "Надёжность", "Логи убивают SD-карту.",
         "Pi на SD: journal на volatile или USB/SSD. Overlayroot для киоска.",
         "Телеметрия 50 Гц в файл на SD — через месяц карта read-only, робот «загадочно» не пишет калибровку.",
         "df -h\nfindmnt",
         ["без мониторинга read-only remount", "swap на SD"],
         "Hardware notes SBC: носитель, политика логов.",
         ["linux-journalctl", "linux-fs", "linux-realtime"]),
        ("realtime", "Realtime Linux: ожидания", "Надёжность", "PREEMPT_RT, isolcpus, нет чуда.",
         "Можно улучшить джиттер шлюза, нельзя честно заменить MCU на Pi для тока мотора.",
         "Если нужен 1 кГц PWM — MCU. Linux — планирование, зрение, сеть.",
         "# isolcpus=3 nohz_full=3 в cmdline — только после измерения",
         ["маркетинг «realtime Pi» как архитектура привода", "SCHED_FIFO без понимания инверсии"],
         "Разделение MCU/SBC на холсте — главное архитектурное решение робота.",
         ["linux-intro", "cpp-embedded", "robotics-control-split"]),
    ])


def git_articles():
    return _pack("git", "Git", [
        ("intro", "Git как память системы", "Основы", "Репозиторий кода, конфигов, не бинарных STL гигабайтов без LFS.",
         "Git фиксирует, почему изменился протокол. Canvas-экспорт JSON тоже можно версионировать.",
         "Прошивка, шлюз, описания регистров — один монорепо или несколько с версиями на связях.",
         "git status\ngit log --oneline",
         ["коммиты «fix» без смысла", "секреты в репозитории"],
         "current_version_label проекта Canvas держите рядом с git tag.",
         ["git-commit", "git-tag", "git-lfs"]),
        ("clone", "clone и remote", "Основы", "Откуда изделие получает код — не git pull на роботе как процесс.",
         "Сборка в CI, на робот — артефакт. git на изделии — исключение для стенда.",
         "Инженер клонирует стенд, робот получает deb/docker.",
         "git clone git@host:org/robot.git",
         ["на изделии ветка develop", "https пароль в unit-файле"],
         "Поставка — отдельный блок CI/CD в будущем; пока notes компонента.",
         ["git-branch", "docker-intro", "linux-systemd"]),
        ("commit", "Коммиты", "Основы", "Атомарность: протокол + парсер Python + парсер C++ вместе.",
         "Изменили кадр UART — один коммит на оба конца и документ message_structure.",
         "Иначе робот в поле с новой прошивкой и старым шлюзом.",
         "git commit -m 'uart: add seq byte to frame v2'",
         ["раздельные коммиты несовместимых концов без версии протокола", "огромный diff с форматером"],
         "Версия протокола на связи Canvas.",
         ["git-diff", "protocols-versioning", "git-tag"]),
        ("branch", "Ветки", "Ветвление", "feature/estop, release/1.4.",
         "Не держите 30 долгоживущих веток прошивки «на всякий борт».",
         "hotfix на роботе №7 — ветка от tag, не от чужого эксперимента SLAM.",
         "git switch -c feature/can-filter",
         ["коммиты напрямую в main на стенде", "ветка на каждого инженера без rebase/merge"],
         "Architecture version в Canvas ≠ git branch, но релизный tag связывает.",
         ["git-merge", "git-tag", "git-commit"]),
        ("merge", "merge", "Ветвление", "Слияние с историей.",
         "Подходит для релизов. Конфликты в картах регистров решайте явно.",
         "Два человека добавили holding register 40010. Нужна таблица, не «оба».",
         "git merge --no-ff release/1.4",
         ["merge без прочтения карты регистров", "игнор конфликтных бинарников"],
         "Документ карты регистров — единственный источник, код — зеркало.",
         ["git-conflict", "git-rebase", "cpp-modbus"]),
        ("rebase", "rebase", "Ветвление", "Линейная история feature.",
         "Не rebase публичных release. Для локальной feature — ок.",
         "Перед PR шлюза rebase на main, прогоните тесты CRC.",
         "git rebase main",
         ["rebase уже запушенной release", "force push в shared ветку прошивки цеха"],
         "Правило команды — в docs репозитория, не в Canvas, но влияет на версию компонента.",
         ["git-merge", "git-commit", "git-remote"]),
        ("conflict", "Конфликты", "Ветвление", "Особенно codegen и IDL.",
         "Конфликт .proto/кадра — остановитесь и свертесь с Canvas protocol.",
         "Семантика важнее, чем «оставить обе стороны».",
         "<<<<<<< HEAD\nmagic = 0xAA\n=======",
         ["принять обе константы magic", "решить конфликт только в Python"],
         "Протокол на холсте — арбитраж конфликта.",
         ["git-merge", "python-struct", "cpp-struct"]),
        ("remote", "push, pull, review", "Совместная работа", "Защита main.",
         "CI на парсеры. Review обязателен на протокол и ESTOP.",
         "Правка ISR ESTOP без ревью — нарушение процесса безопасности.",
         "git push -u origin feature/estop",
         ["force push main", "обход CI «очень надо на выставку»"],
         "Требования must к процессу — в requirements проекта.",
         ["git-tag", "cpp-safety", "git-branch"]),
        ("tag", "Теги и релизы", "Релизы", "v1.4.0-firmware, semver протокола отдельно.",
         "Прошивка, шлюз, схема БД могут версионироваться раздельно, но релиз робота — набор pin.",
         "На холсте version блоков = git tag артефакта.",
         "git tag -a v1.4.0 -m 'drive pid antiwindup'",
         ["один tag на всё при несовместимом UART", "перезапись tag"],
         "Export JSON архитектуры кладите рядом с tag.",
         ["git-commit", "python-packaging", "git-lfs"]),
        ("stash", "stash", "Инструменты", "Карман для локальной грязи.",
         "Не stash на две недели калибровочных коэффициентов — это должен быть файл и коммит.",
         "Переключились посмотреть чужой CAN-фильтр.",
         "git stash push -m 'wip imu bias'",
         ["stash секретов", "потеря stash на другом ПК"],
         "Калибровки — файлы в /var или репозиторий config, не stash.",
         ["git-commit", "python-config", "git-clone"]),
        ("bisect", "bisect", "Инструменты", "Кто сломал одометрию.",
         "Автоматический тест: робот едет 1 м в симе. bisect найдёт коммит.",
         "Регресс после «мелкого рефактора UART».",
         "git bisect start\ngit bisect bad\ngit bisect good v1.3.0",
         ["bisect без воспроизводимого теста", "пропуск коммитов протокола"],
         "Тест одометрии привязан к requirement.",
         ["git-testing-link", "python-testing", "robotics-odometry"]),
        ("lfs", "Git LFS и бинарники", "Релизы", "STL, датасеты, не в обычный git.",
         "STL механики в Canvas — файлы приложения. В git — LFS или artifactory. Не раздувайте клон.",
         "Колесо v2.stl 40 МБ × 80 коммитов убивает CI.",
         "git lfs track '*.stl'",
         ["lfs не поставить на CI runner", "хранить веса нейросети без версии"],
         "AttachedFile в Canvas указывает filename+version. В git — тот же version.",
         ["git-tag", "app-stl", "python-files"]),
    ])


def bash_articles():
    return _pack("bash", "Bash", [
        ("intro", "Bash как клей", "Основы", "Скрипты деплоя, не control loop.",
         "Bash запускает, проверяет, прошивает. Не считает PID.",
         "flash.sh, healthcheck.sh, backup-calib.sh.",
         "#!/usr/bin/env bash\nset -euo pipefail",
         ["bash на 500 строк с логикой навигации", "нет set -euo"],
         "Скрипты — блок Tooling.",
         ["bash-strict", "bash-args", "linux-systemd"]),
        ("strict", "set -euo pipefail", "Основы", "Падать рано.",
         "Незамеченный rm по пустой переменной хуже, чем останов скрипта.",
         "Прошивка: если esptool вернул 1 — не reboot в half-flashed.",
         "set -euo pipefail\ntrap 'echo fail' ERR",
         ["set -e и пайп без pipefail", "маскировка $? в if без причины"],
         "failure_modes tooling: ненулевой код = стоп процедуры.",
         ["bash-intro", "bash-pipes", "bash-traps"]),
        ("vars", "Переменные и кавычки", "Основы", "\"$dev\" vs $dev.",
         "Путь с пробелом, пустой UART — классика уничтожения.",
         "DEVICE=/dev/robot-mcu всегда в кавычках.",
         "flash \"$DEVICE\"",
         ["rm -rf $DIR/ где DIR пуст", "неэкранированный ssh"],
         "Параметры скрипта = конфиг, не хардкод.",
         ["bash-strict", "bash-args", "linux-permissions"]),
        ("args", "Аргументы скрипта", "Основы", "$1, getopts.",
         "Скрипт прошивки принимает --port, --fw, --dry-run.",
         "Оператор в поле не редактирует скрипт.",
         "while getopts p:f:n flag; do ...; done",
         ["позиционные без help", "нет --dry-run на опасных действиях"],
         "CLI tooling совпадает с python argparse утилитами.",
         ["python-argparse", "bash-help", "bash-vars"]),
        ("pipes", "Пайпы и коды возврата", "Поток", "Левая команда молча умерла.",
         "pipefail обязателен. healthcheck: journalctl | grep FAULT — поймите ложные срабатывания.",
         "Цепочка: dump_log | gzip > /var/log/robot/x.gz",
         "cmd1 | cmd2",
         ["проверка только $? последней", "grep без || true там, где 1 = «не найдено» норма"],
         "Алгоритм процедуры бэкапа логов.",
         ["bash-strict", "linux-journalctl", "bash-redirects"]),
        ("redirects", "Перенаправления", "Поток", "stdin/out/err, tee.",
         "Лог прошивки в файл и на экран: tee. Пароль не в лог.",
         "esptool 2>&1 | tee flash.log",
         "make 2>&1 | tee build.log",
         ["закрыть stdin сервиса так, что serial отвалился", "перезаписать калибровку > вместо >> без бэкапа"],
         "Артефакты flash.log — attached notes версии.",
         ["bash-pipes", "linux-fs", "git-lfs"]),
        ("if", "if, test, [[ ]]", "Поток", "Проверки устройства.",
         "Перед стартом сервиса: есть ли /dev/robot-mcu. Нет — не стартовать RUN, unit failed.",
         "ExecStartPre=/usr/lib/robot/check-dev.sh",
         "if [[ ! -e /dev/robot-mcu ]]; then exit 1; fi",
         ["-e vs -L на symlink udev", "проверка ping как «MCU жив» без протокола"],
         "Precondition компонента шлюза.",
         ["linux-udev", "linux-systemd", "bash-strict"]),
        ("loops", "Циклы", "Поток", "Ожидание устройства, не busy forever.",
         "Ждать udev 10 секунд с backoff. Дальше fail.",
         "Камера появляется позже бута.",
         "for i in {1..20}; do [[ -e /dev/video0 ]] && break; sleep 0.5; done",
         ["while true без timeout", "sleep 30 «на всякий» в unit"],
         "Таймаут ожидания — requirement на старт системы.",
         ["bash-if", "linux-udev", "bash-traps"]),
        ("functions", "Функции bash", "Структура", "Повторяемые шаги flash.",
         "need_cmd, die, wait_dev — короткие функции. Не копипаста 4 раз.",
         "Одинаковый wait_dev для IMU и MCU.",
         "die() { echo \"$*\" >&2; exit 1; }",
         ["функции, меняющие глобальные без local", "имя cd внутри функции без pushd"],
         "Скрипт как вложенный алгоритм блока Tooling.",
         ["bash-traps", "bash-strict", "python-functions"]),
        ("grep", "grep, rg, journal", "Текст", "Искать FAULT аккуратно.",
         "Фиксированные паттерны. Цвет ломает пайпы — --no-color.",
         "Алерт: три FAULT за минуту.",
         "journalctl -u robot-svc | grep -E 'FAULT|ESTOP'",
         ["grep по всему диску на роботе", "ложный матч в hex-дампе"],
         "Словарь событий согласован с логами Python/C++.",
         ["linux-journalctl", "python-logging", "bash-awk"]),
        ("find", "find и чистка артефактов", "Текст", "Ротация csv телеметрии.",
         "Удалять старше N дней, не rm *. На SD критично.",
         "Каталог /var/lib/robot/telem",
         "find /var/lib/robot/telem -mtime +7 -delete",
         ["find без -print0 при пробелах", "удаление калибровок тем же правилом"],
         "Политика данных — docs SBC.",
         ["linux-disks", "bash-redirects", "python-files"]),
        ("cron", "cron/timers systemd", "Расписание", "Бэкап, не контроль.",
         "systemd timer лучше cron на изделии: логи, зависимостей.",
         "Ночной бэкап калибровок на USB.",
         "OnCalendar=*-*-* 03:00:00",
         ["cron с GUI-окружением", "задача, которая двигает робота"],
         "Блок maintenance на холсте операций.",
         ["linux-systemd", "bash-intro", "linux-disks"]),
        ("traps", "trap и безопасное прерывание", "Надёжность", "Снять адаптер, размотировать lock.",
         "Ctrl+C во время flash: не оставить boot0 в странном состоянии, если можете.",
         "lock-файл /run/robot-flash.lock",
         "trap 'rm -f $LOCK' EXIT",
         ["trap, который игнорирует INT на опасной операции без сообщения", "нет lock — две прошивки сразу"],
         "Процедура flash — алгоритм с отменой.",
         ["bash-strict", "cpp-gdb", "linux-processes"]),
        ("help", "set -x и отладка", "Надёжность", "Видно команду, не секреты.",
         "PS4 и xtrace. Маскируйте токены MQTT.",
         "Почему scp не туда — видно с -x.",
         "bash -x ./flash.sh --dry-run",
         ["-x в проде с паролями", "отладка на живых моторах"],
         "Стенд tooling отдельно от RUN.",
         ["bash-args", "linux-ssh", "bash-strict"]),
    ])


def sql_articles():
    return _pack("sql", "SQL", [
        ("intro", "SQL в робототехническом стеке", "Основы", "Что хранить: не тики 1 кГц.",
         "БД — миссии, пользователи, события, калибровки, BOM-ссылки. Не поток IMU. Для потока — файлы, TSDB, брокер.",
         "Таблица missions, events, devices. Телеметрия 100 Гц — Timescale/файлы, отдельное решение.",
         "SELECT now();",
         ["писать каждый сэмпл IMU в Postgres на SD", "один JSON-столбец «на всё» без нужды"],
         "Режим База данных в Canvas — семантическая ER, затем Export SQL.",
         ["sql-select", "databases-choose", "app-er"]),
        ("select", "SELECT и проекция", "Чтение", "Только нужные колонки.",
         "Операторский UI не тянет BYTEA карт. Список миссий — id, name, status.",
         "Экран «последние FAULT» — узкий select.",
         "SELECT id, code, created_at FROM events WHERE severity = 'FAULT';",
         ["SELECT * в API", "отсутствие LIMIT на бесконечном журнале"],
         "Колонки таблицы в ER = контракт API list-эндпоинта.",
         ["sql-where", "sql-index", "python-fastapi"]),
        ("where", "WHERE и предикаты", "Чтение", "Фильтры событий робота.",
         "Индексируемые предикаты. Не оборачивайте колонку в функцию, если нужен индекс.",
         "События робота_id и времени — типичный фильтр.",
         "WHERE robot_id = $1 AND created_at >= $2",
         ["WHERE DATE(created_at)=today() на большом журнале", "строковое сравнение uuid"],
         "Индексы нарисуйте в инспекторе таблицы.",
         ["sql-index", "sql-join", "sql-explain"]),
        ("join", "JOIN", "Чтение", "Пользователи и миссии, устройства и события.",
         "1–N как на ER-холсте. JOIN в SQL должен совпасть с Connection cardinality.",
         "users 1—N projects в учебном примере Canvas.",
         "SELECT p.name, u.login FROM projects p JOIN users u ON u.id = p.user_id;",
         ["JOIN без ключей, декартово", "N–N без промежуточной таблицы"],
         "Связь таблиц на ER = JOIN. SQL export это проверяет.",
         ["sql-er", "sql-keys", "app-er"]),
        ("group", "GROUP BY и агрегаты", "Чтение", "Сколько FAULT за смену.",
         "COUNT/AVG по robot_id. HAVING после агрегата.",
         "Дашборд парка роботов, не realtime PID.",
         "SELECT robot_id, COUNT(*) FROM events WHERE code='FAULT' GROUP BY robot_id;",
         ["SELECT * с GROUP BY некорректно", "агрегат в приложении циклом без нужды"],
         "Отчётные запросы — документ блока Analytics, если появится.",
         ["sql-select", "sql-index", "sql-explain"]),
        ("keys", "PRIMARY/UNIQUE/FK", "Схема", "Целостность важнее удобства JSON.",
         "PK, UNIQUE login, FK user_id. ON DELETE согласуйте с доменом: нельзя молча удалить робота с журналом безопасности.",
         "Удаление устройства — политика. Для аудита чаще RESTRICT.",
         "ALTER TABLE projects ADD CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id);",
         ["нет FK «потому что ORM»", "каскад, стирающий audit"],
         "ER-связи Canvas генерируют FK. Проверьте cardinality.",
         ["sql-join", "sql-er", "sql-tx"]),
        ("index", "Индексы", "Схема", "B-tree на фильтры, не на всё.",
         "Индекс (robot_id, created_at) под журнал. Лишние индексы бьют запись калибровок.",
         "Вставка события FAULT не должна тормозить из-за 12 индексов «на будущее».",
         "CREATE INDEX idx_events_robot_time ON events (robot_id, created_at);",
         ["уникальный индекс на часто меняющееся float", "индекс как замена нормализации"],
         "Table indexes в инспекторе. SQL export пишет CREATE INDEX.",
         ["sql-explain", "sql-where", "databases-postgres"]),
        ("tx", "Транзакции", "Запись", "Атомарность миссии.",
         "Создать миссию + точки маршрута — одна транзакция. Иначе полусохранённый маршрут.",
         "BEGIN; INSERT mission; INSERT waypoints; COMMIT;",
         "BEGIN;\nINSERT INTO missions(name) VALUES ('dock');\nCOMMIT;",
         ["автокоммит по строке в загрузчике карты", "длинная транзакция на UI-клик с сетью"],
         "Инварианты — requirements + транзакция в сервисе.",
         ["sql-isolation", "python-fastapi", "sql-keys"]),
        ("isolation", "Изоляция и гонки", "Запись", "Два оператора, одна миссия.",
         "Повторный START. Optimistic lock version или SELECT FOR UPDATE осознанно.",
         "Два UI отправили run. БД или супервизор — единственный арбитр.",
         "-- version INT, UPDATE ... WHERE version=$old",
         ["потерянный апдейт статуса", "FOR UPDATE на всю таблицу events"],
         "Состояние RUN живёт в супервизоре. БД — факт миссии, не PWM.",
         ["sql-tx", "python-state-machine", "sql-status"]),
        ("explain", "EXPLAIN", "Производительность", "Seq scan журнала.",
         "Перед продакшеном журнала — EXPLAIN ANALYZE на типичный фильтр.",
         "UI «события за сутки» не должен сканировать год.",
         "EXPLAIN ANALYZE SELECT * FROM events WHERE robot_id=1;",
         ["игнор seq scan потому что «данных мало» на стенде", "оптимизация без измерения"],
         "Notes таблицы: ожидаемый объём и запросы UI.",
         ["sql-index", "sql-where", "databases-postgres"]),
        ("crud", "INSERT/UPDATE/DELETE", "Запись", "Идемпотентность команд.",
         "Повтор HTTP не должен плодить 3 миссии. UNIQUE + upsert где нужно.",
         "Кнопка «сохранить карту» дважды.",
         "INSERT INTO maps(id, body) VALUES ($1,$2) ON CONFLICT (id) DO UPDATE SET body=EXCLUDED.body;",
         ["DELETE FROM без WHERE", "update статуса без where id"],
         "API компонента Data = эти операторы. ER показывает таблицы.",
         ["sql-keys", "sql-tx", "python-pydantic"]),
        ("jsonb", "JSON в SQL", "Типы SQL", "Гибкость vs ER.",
         "JSONB для редких атрибутов устройства. Колонками — то, по чему фильтруете и связываете.",
         "params калибровки можно JSONB. robot_id — колонка.",
         "SELECT params->>'bias_x' FROM imu_calib;",
         ["вся архитектура в одном jsonb", "поиск по jsonb без GIN, удивляясь тормозам"],
         "Если поле в ER-колонке, не дублируйте только в JSON.",
         ["sql-select", "databases-postgres", "python-json"]),
        ("er", "ER и генерация SQL", "Практика Canvas", "Таблица как компонент.",
         "В Architecture Canvas таблица — сущность с колонками. Связь 1–N создаёт FK. N–N — junction в SQL.",
         "Спроектируйте users/projects, затем диалект PostgreSQL и скачайте .sql.",
         "-- CREATE TABLE users (...);\n-- CONSTRAINT fk_ ...",
         ["рисовать ER картинкой вне модели", "имена таблиц с пробелами без правил"],
         "Раздел База данных слева. Инспектор колонок. Экспорт SQL.",
         ["app-er", "sql-keys", "sql-join"]),
        ("views", "VIEW", "Практика Canvas", "Готовые срезы для UI.",
         "VIEW last_faults — не путать с таблицей. Обновляемость ограничена.",
         "Оператор видит безопасный срез без PII, если спрячете колонки.",
         "CREATE VIEW last_faults AS SELECT ...;",
         ["вместо индекса сделать view и ждать ускорения", "view, скрывающая тяжёлый join без docs"],
         "В будущем entity view. Сейчас — notes/SQL вручную после базовых таблиц.",
         ["sql-select", "sql-er", "app-er"]),
    ])


def docker_articles():
    return _pack("docker", "Docker", [
        ("intro", "Контейнер ≠ виртуальный MCU", "Основы", "Изоляция Linux-сервисов.",
         "Docker пакует шлюз, брокер, UI. Прошивку STM32 он не заменяет. RT-потоки внутри контейнера требуют --privileged/device аккуратно.",
         "compose: mosquitto, robot-svc, web. MCU снаружи, проброшен /dev/robot-mcu.",
         "FROM python:3.11-slim",
         ["контейнеризовать всё включая hard realtime без измерения", "привилегии всем подряд"],
         "Блок Docker как модуль ПО или notes runtime у Backend.",
         ["docker-file", "docker-devices", "linux-intro"]),
        ("file", "Dockerfile", "Образы", "Слои, пользователь, pin базового образа.",
         "Не root в runtime. Копируйте только нужное. Мультистейдж для сборки C++ gateway.",
         "Образ шлюза с pyserial. Пользователь robot uid совпадает с udev groups — проще на host network/device.",
         "RUN useradd -r robot\nUSER robot",
         ["latest теги", "секреты в слое ENV"],
         "Версия образа = version компонента.",
         ["docker-multi", "docker-compose", "python-packaging"]),
        ("compose", "Compose", "Оркестрация", "Локальный и бортовой стек.",
         "Зависимости healthcheck: брокер healthy → шлюз. restart policies как systemd.",
         "Ноут инженера и робот — один compose с overlay device.",
         "depends_on:\n  mqtt:\n    condition: service_healthy",
         ["depends_on без health — гонка", "volume на всё /"],
         "Несколько software-блоков = несколько сервисов compose, связи = сети/топики.",
         ["docker-networks", "docker-health", "linux-systemd"]),
        ("volumes", "Тома", "Данные", "Калибровки переживают обновление образа.",
         "Named volume /var/lib/robot. Не храните прошивку-секреты в образе.",
         "Обновили шлюз — IMU bias на месте.",
         "volumes:\n  - robot-data:/var/lib/robot",
         ["bind-mount всей домашней папки", "забыть uid volume"],
         "Paths как в linux-fs статье, согласованные.",
         ["linux-fs", "docker-compose", "python-config"]),
        ("networks", "Сети Docker", "Сеть", "Изоляция брокера.",
         "Внутренний bridge для mqtt/api. Публикуйте только UI порт. Host network — исключение для сканирования UDP лидара.",
         "Лидар multicast иногда проще host network — опишите это как осознанный компромисс.",
         "expose: ['1883']",
         ["0.0.0.0 публикация брокера без ACL", "два compose-проекта с пересечением подсетей и удивлением"],
         "Связи NETWORK на холсте = какие порты реально открыты.",
         ["linux-firewall", "docker-compose", "protocols-mqtt"]),
        ("devices", "Устройства и privileged", "Железо", "Прокидывать точечно.",
         "devices: /dev/robot-mcu. privileged почти всегда лишний и опасный.",
         "Шлюз в контейнере говорит с STM32. udev на хосте создаёт имя, контейнер видит device.",
         "devices:\n  - /dev/robot-mcu:/dev/robot-mcu",
         ["privileged: true «потому что serial»", "нет group_add dialout"],
         "Документируйте runtime у блока Gateway.",
         ["linux-udev", "python-serial", "docker-file"]),
        ("logs", "Логи контейнера", "Наблюдаемость", "json-file limits.",
         "max-size, max-file. Иначе SD снова умрёт. Можно journald driver.",
         "Телеметрия не в stdout 100 Гц.",
         "logging:\n  options:\n    max-size: \"10m\"",
         ["без лимита на камеру debug", "секреты в логе healthcheck"],
         "Согласуйте с python-logging: уровни, не дамп кадра.",
         ["linux-disks", "linux-journalctl", "docker-compose"]),
        ("health", "Healthcheck", "Наблюдаемость", "Не ping, а «шина жива».",
         "HTTP /health: mqtt connected, last mcu frame < 200ms. Иначе не ready.",
         "Оркестратор не шлёт трафик в полумёртвый шлюз.",
         "HEALTHCHECK CMD curl -f localhost:8000/health",
         ["health всегда 200", "health, который ходит в тяжёлый SLAM"],
         "API health — часть блока Backend.",
         ["docker-compose", "python-fastapi", "linux-systemd"]),
        ("multi", "Multi-stage", "Образы", "Сборка C++ отдельно от runtime.",
         "builder с g++, runtime slim. Меньше CVE поверхность.",
         "gateway бинарник копируется в distroless/slim.",
         "FROM debian AS build\nFROM debian-slim",
         ["оставить compiler в prod", "разные glibc builder/runtime без проверки"],
         "Таргеты CMake совпадают со стадиями.",
         ["cpp-cmake", "docker-file", "docker-sec"]),
        ("sec", "Минимальная безопасность", "Практика", "Non-root, read-only FS, no-new-privileges.",
         "read_only + tmpfs. Capabilities drop. Это не IEC, но отсекает глупости.",
         "Контейнер UI не видит /dev.",
         "security_opt: ['no-new-privileges:true']",
         ["сокет docker.sock внутрь приложения", "root + privileged + host pid"],
         "Требования безопасности на runtime.",
         ["linux-permissions", "docker-devices", "linux-firewall"]),
        ("sim", "Симуляция в контейнерах", "Практика", "Gazebo/симы как профили compose.",
         "Профиль sim поднимает fake-mcu. Профиль hw — devices. Один и тот же шлюз.",
         "CI гоняет sim профиль. Это ваши FakeBus из Python Protocol.",
         "# compose --profile sim up",
         ["один образ, который сам угадывает есть ли железо, без явного профиля", "сим и hw одновременно на одни топики"],
         "Вложенный холст Test/Sim vs Hardware.",
         ["python-protocols-abc", "docker-compose", "robotics-sim"]),
        ("ci", "Образы в CI", "Практика", "Теги sha, не latest на роботе.",
         "Робот pin digest. latest только на стенде инженера.",
         "Откат — предыдущий digest, не «починить на живую».",
         "image: registry/robot-svc@sha256:...",
         ["pull latest ночью без тестов", "разный digest на двух колёсных роботах «одного парка» без учёта"],
         "version компонента = digest/tag.",
         ["git-tag", "docker-file", "python-packaging"]),
    ])


def databases_articles():
    return _pack("databases", "Databases", [
        ("intro", "Зачем БД роботу", "Выбор", "Состояние мира vs поток сенсоров.",
         "БД хранит факты: кто, какая миссия, какая калибровка, какой BOM. Поток лидара — не Postgres на SD.",
         "Супервизор — источник RUN. БД — журнал и конфигурация.",
         "-- missions, devices, events, calib",
         ["заменить брокер базой", "хранить STL в bytea без нужды"],
         "ER-диаграмма проекта. Блок PostgreSQL на системном холсте — runtime, таблицы — на холсте БД.",
         ["sql-intro", "databases-choose", "app-er"]),
        ("choose", "Как выбрать движок", "Выбор", "SQLite, Postgres, Redis, ничего.",
         "Один робот оффлайн — SQLite. Парк + UI — Postgres. Кэш/сессии — Redis. MCU — не БД.",
         "Тележка в поле без сети: SQLite на SBC. Диспетчерская — Postgres.",
         "-- sqlite3 robot.db\n-- postgres dsn",
         ["Mongo «потому что JSON» без модели", "Redis как единственное хранилище миссий"],
         "Поле dialect у DatabaseInfo и тип блока DATA.",
         ["databases-sqlite", "databases-postgres", "databases-redis"]),
        ("sqlite", "SQLite", "Движки", "Файл, транзакции, ограничения записи.",
         "Один writer. Отлично для конфигов и локального журнала. Бэкап = файл.",
         "Калибровки и last_mission на Pi. Не 200 Гц insert.",
         "PRAGMA journal_mode=WAL;",
         ["сеть NFS и SQLite", "многопроцессная запись без очереди"],
         "Файл БД — path в docs SBC. ER та же, диалект sqlite в экспорте.",
         ["sql-tx", "linux-disks", "databases-choose"]),
        ("postgres", "PostgreSQL", "Движки", "Парк, JSONB, надёжный SQL.",
         "Роли, timestamptz, FK. Основной диалект экспорта Canvas.",
         "Диспетчер, пользователи, отчёты FAULT по смене.",
         "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
         ["суперпользователь из приложения", "без бэкапов WAL"],
         "Блок PostgreSQL + холст таблиц. SQL export postgresql.",
         ["sql-jsonb", "sql-index", "databases-backup"]),
        ("mysql", "MySQL/MariaDB", "Движки", "Когда уже стоит на заводе.",
         "Часто данность IT. Типы и JSON отличаются. Экспорт Canvas умеет mysql.",
         "Интеграция с существущим MES, не «ещё один Postgres назло».",
         "-- ENGINE=InnoDB",
         ["MyISAM для журнала безопасности", "разный sql_mode на стенде и заводе"],
         "Выберите диалект MySQL в панели SQL.",
         ["sql-er", "databases-choose", "sql-tx"]),
        ("redis", "Redis", "Движки", "Кэш, очередь, не система записи правды.",
         "Последняя телеметрия для UI, lock, rate limit. Миссии — в SQL.",
         "Ключ robot:{id}:pose с TTL. Рестарт Redis не должен забывать маршрут в SQL.",
         "SET robot:1:pose '{...}' EX 2",
         ["единственное хранилище ESTOP в Redis", "без TTL и утечка ключей"],
         "Блок Redis категории DATA. Связь с Backend — протокол Redis/TCP.",
         ["python-queues", "databases-choose", "protocols-tcp"]),
        ("migrate", "Миграции", "Эволюция", "Версия схемы = версия компонента Data.",
         "Alembic/Flyway. Запрет «ALTER руками на проде» без записи.",
         "Добавили колонку firmware_sha — миграция + поле на холсте таблицы devices.",
         "-- alembic upgrade head",
         ["менять ER в Canvas и забывать миграцию", "destructive drop на поле"],
         "Версия схемы в notes блока БД. ER и миграции не должны расходиться.",
         ["sql-er", "git-tag", "python-packaging"]),
        ("backup", "Бэкапы и restore", "Эволюция", "Журнал безопасности имеет ценность.",
         "pg_dump по расписанию. Проверяйте restore. SQLite — копируйте файл атомарно.",
         "После инцидента нужны события, не «диск умер вместе с правдой».",
         "pg_dump -Fc robot > robot.dump",
         ["бэкап рядом на той же SD", "никогда не пробовали restore"],
         "Требование must: хранение журнала N суток.",
         ["linux-cron", "databases-postgres", "linux-disks"]),
        ("pool", "Пулы соединений", "Эксплуатация", "Не коннект на каждый MQTT.",
         "HTTP API держит pool. Фоновый consumer — свой бюджет коннектов.",
         "Шлюз не открывает Postgres на каждый кадр IMU.",
         "-- pool_size=5",
         ["утечка коннектов при исключении", "pool больше чем max_connections"],
         "Notes Backend: кто ходит в БД. MCU — никто.",
         ["python-fastapi", "databases-postgres", "sql-tx"]),
        ("tsdb", "Временные ряды", "Потоки", "Когда SQL уже не тот инструмент.",
         "Timescale/Influx/файлы parquet. Отдельный контур от OLTP миссий.",
         "График тока за смену — TSDB. Список миссий — Postgres.",
         "-- hypertable(ts, robot_id)",
         ["гипертаблица «на всё» включая users", "высокая cardinality id без плана"],
         "Не смешивайте на одном ER-холсте OLTP и 10кГц ряды без необходимости.",
         ["sql-intro", "databases-choose", "python-generators"]),
        ("sync", "Синхронизация борт↔облако", "Потоки", "Оффлайн очередь.",
         "Робот копит события, при сети — upload. Идемпотентные id.",
         "Шахта/поле: связь пропадает. Миссии не теряются.",
         "-- UUID pk, replicated_at",
         ["wall clock как id", "синхронный insert в облако из control loop"],
         "Блок External Service + очередь. Протокол HTTPS/MQTT.",
         ["sql-crud", "networking-nat", "python-asyncio"]),
        ("er-practice", "Практика модели в Canvas", "Практика", "Database, schema, table, relation.",
         "Создайте architecture kind=database. Таблицы — компоненты. Связи — cardinality.",
         "users→projects 1–N, junction для N–N в SQL.",
         "-- см. Export SQL",
         ["хранить ER скриншотом", "FK не тем концом"],
         "Раздел «База данных». Инспектор колонок PK/FK. Скачать .sql.",
         ["sql-er", "app-er", "sql-keys"]),
    ])


def networking_articles():
    return _pack("networking", "Networking", [
        ("intro", "Сеть как часть машины", "Основы", "Не «просто Wi-Fi».",
         "OT-сеть робота: детерминизм, сегментация, диагностика. Офисный Wi-Fi — враг ШИМ только если вы туда засунули control.",
         "MCU—драйвер: не Ethernet. Камера GigE — Ethernet. UI — Wi-Fi.",
         "OSI: L1 кабель/радио → L4 TCP/UDP → L7 MQTT",
         ["весь control через облако", "одна плоская сеть гостей и приводов"],
         "Связи NETWORK/PROTOCOL на холсте с указанием L4.",
         ["networking-l2", "networking-tcp", "linux-net-tools"]),
        ("l2", "Ethernet, PHY, разъёмы", "Низкий уровень", "Экранирование, PoE камер.",
         "Вибрация + дешёвые RJ45 = плавающие лидары. Промышленные M12.",
         "Камера на манипуляторе — кабель как механический элемент (BOM).",
         "ethtool eth0",
         ["питание камеры только PoE без расчёта бюджета", "U/UTP вдоль силового мотора без меры"],
         "Кабель — mechanical/harness будущего; пока notes Camera + Ethernet.",
         ["electronics-ground", "robotics-sensors", "networking-wifi"]),
        ("ip", "IP, адреса, DHCP vs static", "L3", "Фиксируйте адреса OT.",
         "Камера 192.168.10.20 static. DHCP — для UI ноутбука, не для лидара в цикле.",
         "После ребута роутера лидар не должен сменить адрес.",
         "ip addr add 192.168.10.5/24 dev eth0",
         ["два DHCP сервера в шкафу", "один адрес на два устройства"],
         "Адреса в docs Network Device / Camera.",
         ["networking-dns", "linux-net-tools", "networking-nat"]),
        ("tcp", "TCP", "L4", "Потоки, гарантия, не realtime.",
         "HTTP, MQTT (обычно), Modbus TCP. Ретрансмиссии дают джиттер — не кладите сюда ток мотора.",
         "Конфиг и команды миссии — TCP. Setpoint 1 кГц — нет.",
         "ss -ti",
         ["Nagle + маленькие setpoint", "бесконечный keepalive без приложения"],
         "Протокол TCP/HTTP цвет линии. Notes: зачем TCP, а не UDP.",
         ["networking-udp", "protocols-http", "cpp-chrono"]),
        ("udp", "UDP", "L4", "Потоки сенсоров, потеря — норма.",
         "Лидар/видео часто UDP. Контроль потерь на прикладном уровне (seq).",
         "Потеря кадра — хуже, чем джиттер TCP 200 мс для телеметрии UI? Зависит. Для SLAM иногда drop лучше stall.",
         "socat - UDP:192.168.10.20:2368",
         ["считать UDP «ненадёжным значит бесполезным»", "нет seq и вы собираете облако из разных оборотов"],
         "data_flow Lidar: UDP, частота, что при потере.",
         ["networking-tcp", "robotics-slam", "python-struct"]),
        ("dns", "DNS и mDNS", "L3", "Имена в цехе.",
         "Не завязывайте привод на DNS облака. Локальные имена или /etc/hosts/OT DNS.",
         "Брокер mqtt.ot.local. Падение интернета не должно останавливать RUN, если миссия локальная.",
         "getent hosts mqtt.ot.local",
         ["таймаут DNS 5 с в control", "публичный DNS для имени камеры"],
         "Зависимости компонента: DNS нужен/не нужен в RUN.",
         ["networking-ip", "linux-net-tools", "protocols-mqtt"]),
        ("nat", "NAT, маршруты, VPN", "L3", "Удалённая диагностика.",
         "VPN инженера в OT, не проброс MQTT в интернет. NAT скрывает борт — заложите порты явно.",
         "Поддержка в поле через WireGuard jump host.",
         "ip route",
         ["проброс 1883 на 0.0.0.0 мира", "два VPN с overlapping 10.0.0.0/8"],
         "Блок External Access. Требования безопасности.",
         ["linux-ssh", "linux-firewall", "networking-wifi"]),
        ("wifi", "Wi-Fi", "Радио", "Не шина привода.",
         "Телеметрия/UI. Роуминг, канал, индустриальные AP. 2.4 ГГц грязный.",
         "Операторский планшет. Не FOC.",
         "iw dev wlan0 link",
         ["control ESTOP по Wi-Fi как единственный канал", "скрытая сеть без плана"],
         "Связь Wi-Fi цвет/протокол. ESTOP — провод.",
         ["cpp-safety", "networking-intro", "protocols-mqtt"]),
        ("qos-net", "QoS и приоритеты", "Эксплуатация", "Видео не душит команды.",
         "Отдельные VLAN: vision / ui / unused for drive. DSCP если умеете.",
         "4K камера на том же свитче, что Modbus TCP к ПЛК — классика боли.",
         "VLAN 10 OT, VLAN 20 vision",
         ["один switch unmanaged на всё", "QoS только на бумаге"],
         "Коммутатор — блок NETWORK. VLAN в notes.",
         ["networking-l2", "protocols-modbus", "linux-firewall"]),
        ("tls", "TLS и сертификаты", "Безопасность", "MQTT/HTTPS в парке.",
         "Сертификаты с сроком. Провизия на борт. Не самоподписанный навечно без процедуры.",
         "Брокер с TLS между цехами. Внутри шкафа — риск/решение явное.",
         "openssl s_client -connect mqtt:8883",
         ["отключить verify «временно»", "один сертификат на всех роботов без учёта"],
         "Протокол MQTT/HTTPS: port 8883, notes TLS.",
         ["protocols-mqtt", "protocols-http", "linux-ssh"]),
        ("debug", "Диагностика сети", "Эксплуатация", "Слой за слоем.",
         "Link → IP → порт → прикладной handshake. Не начинайте с переписывания Python.",
         "Нет телеметрии: ping брокера, ss, логи ACL, потом код.",
         "ping -c 3 192.168.10.1; tcpdump -n port 1883",
         ["менять PID потому что «сеть лагает»", "dump без фильтра на GigE"],
         "Чек-лист в docs Gateway.",
         ["linux-net-tools", "networking-tcp", "protocols-mqtt"]),
        ("time-sync", "Синхронизация времени", "Эксплуатация", "Логи и сенсоры.",
         "NTP/PTP для штампов камер и журнала. Контур MCU — свои часы. Не путать.",
         "Склейка видео и CAN логов для разбора инцидента.",
         "timedatectl status",
         ["wall clock в PID", "разъехавшиеся часы двух SBC"],
         "Штампы в ER events — timestamptz. В PID — monotonic.",
         ["python-datetime", "cpp-chrono", "sql-intro"]),
    ])


def protocols_articles():
    return _pack("protocols", "Protocols", [
        ("intro", "Протокол — контракт связи", "Основы", "Не цвет линии ради цвета.",
         "Протокол задаёт поля, время, ошибки, адресацию. Canvas хранит это в сущности Protocol + Connection.",
         "MCU↔Python: свой кадр. UI↔Backend: HTTP. Датчики: I²C. Не смешивайте в одной «магистрали без имени».",
         "name, transport, port, data_format, timeout, retry, crc",
         ["одна связь «данные» на всё", "разные версии кадра без version"],
         "Каталог протоколов + цвет ребра + data_example.",
         ["protocols-versioning", "app-protocols", "python-struct"]),
        ("versioning", "Версии протоколов", "Основы", "Несовместимость как событие.",
         "Байт version в кадре или major в topic. Шлюз отвергает неизвестное.",
         "Прошили MCU v2, шлюз v1 — лучше FAULT, чем тихий разбор не туда.",
         "struct { uint8_t ver; ...}",
         ["молча игнорировать лишние байты без версии", "один топик на v1 и v2 JSON разной формы"],
         "Поле version у Protocol. Связь указывает протокол.",
         ["cpp-struct", "git-commit", "protocols-intro"]),
        ("http", "HTTP/HTTPS", "Прикладные", "Команды и REST, не тик.",
         "Идемпотентность GET, команды POST с id. TLS между цехами.",
         "Старт миссии, загрузка карты, статус.",
         "POST /cmd/twist  {\"vx\":0.2,\"wz\":0}",
         ["PUT уставки колёс 50 Гц", "нет auth на /cmd"],
         "Протокол HTTP цвет. API блок. Pydantic схемы.",
         ["python-fastapi", "networking-tls", "python-pydantic"]),
        ("mqtt", "MQTT", "Прикладные", "Шина телеметрии.",
         "Topic hierarchy, QoS, retain, LWT. Retain команд движения запрещён.",
         "robot/{id}/imu, robot/{id}/status, robot/{id}/cmd.",
         "publish robot/1/status online",
         ["retain на cmd", "QoS2 везде «на всякий»", "ESTOP только MQTT"],
         "Блок брокера опционален. Рёбра MQTT. Notes QoS/LWT.",
         ["python-mqtt", "cpp-safety", "networking-tls"]),
        ("websocket", "WebSocket", "Прикладные", "UI телеметрия.",
         "Поток поз в браузер. Переподключение, backpressure, не control 1 кГц.",
         "Оператор видит pose 10 Гц.",
         "ws://gateway/stream/pose",
         ["без ping/pong и тихие мертвецы", "очередь без drop-old"],
         "Связь Frontend—Backend WebSocket.",
         ["python-asyncio", "python-queues", "protocols-http"]),
        ("modbus", "Modbus TCP/RTU", "Полевые", "Регистры как API ПЛК.",
         "Карта регистров — документ. Адрес 40001 путают с 0. RTU нужен CRC и 3.5 символа тишины.",
         "ПЛК держит концевики, Python читает discretes, не наоборот без нужды.",
         "function 3, 4, 6, 16",
         ["off-by-one карты", "два мастера RTU"],
         "Протокол Modbus цвет. Карта — Documentation ПЛК.",
         ["cpp-modbus", "sql-er", "electronics-uart"]),
        ("can", "CAN / CANopen идея", "Полевые", "Шина приводов.",
         "Bitrate, termination 120Ω, id, DLC. Bus-off обработка. Прикладной протокол поверх (свой или CANopen).",
         "Сервоприводы и MCU. Шлюз SocketCAN — Linux-блок.",
         "id 0x101 DLC 8",
         ["без терминаторов", "смешать 250k и 500k", "игнор error counters"],
         "Протокол CAN. Физика в electronics. Прикладной кадр в message_structure.",
         ["cpp-can", "electronics-can", "python-struct"]),
        ("uart", "UART/Serial", "Полевые", "Байтовый поток.",
         "8N1, baud, кадрирование прикладное. Flow control редко, но RTS/CTS на длинных линиях.",
         "Pi—STM32 115200. Watchdog кадра.",
         "115200 8N1",
         ["разный baud", "нет framing", "timeout=None"],
         "Связь UART цвет. Алгоритм сборки кадра.",
         ["python-serial", "cpp-uart", "electronics-uart"]),
        ("spi", "SPI", "Полевые", "Четыре провода, режимы 0–3.",
         "CLK/MOSI/MISO/CS. Частота из datasheet. Один мастер.",
         "IMU, энкодер, SD. Не «SPI в облако».",
         "mode 3, 8 MHz",
         ["не тот mode", "CS общим без транзакций"],
         "Протокол SPI. Datasheet IMU в docs.",
         ["cpp-spi", "electronics-datasheet", "cpp-raii"]),
        ("i2c", "I²C", "Полевые", "Адреса, pull-up, NACK.",
         "7-bit addr, 4.7k pull-up типово, смотрите емкость шины. Clock stretch timeout.",
         "Несколько датчиков — уникальные адреса или мультиплексор как блок.",
         "addr 0x68",
         ["два устройства 0x68", "нет timeout на SCL"],
         "Шина как компонент или пучок связей I²C.",
         ["cpp-i2c", "electronics-pullup", "electronics-datasheet"]),
        ("opcua", "OPC UA", "Индустрия", "Модель узлов, не «ещё JSON».",
         "ПЛК и SCADA. Security policy. Подписка на items vs опрос.",
         "Завод хочет видеть робота как OPC-сервер. Шлюз — отдельный блок, не MCU.",
         "opc.tcp://host:4840",
         ["Anonymous в проде без решения", "подписка 1 мс на всё"],
         "Протокол OPC UA. Блок Gateway к IT/OT.",
         ["protocols-modbus", "sw-integration", "networking-tls"]),
        ("protobuf", "Protobuf/IDL", "Контракты", "Схема вместо свободного JSON.",
         "Версионируемые поля. Генерация Python и C++ из одного .proto.",
         "Команды Twist между сервисами. На MCU часто всё же packed struct — не тащите protobuf на M0 без нужды.",
         "message Twist { float vx = 1; float wz = 2; }",
         ["ломать field numbers", "proto на 32k RAM MCU"],
         "Файл .proto — attached doc компонента. Версия в Protocol.",
         ["protocols-versioning", "python-struct", "cpp-struct"]),
        ("choose", "Как выбрать протокол", "Практика", "Таблица решений.",
         "Расстояние, число узлов, realtime, наличие MCU, IT-требования. Не мода.",
         "1 м до IMU — I²C/SPI. 20 м до ПЛК — Modbus/CAN. UI — HTTP. Парк — MQTT.",
         "матрица: latency, topology, tooling",
         ["MQTT потому что статья", "CAN внутри одной платы без нужды"],
         "Каждое ребро холста — осознанный протокол.",
         ["protocols-intro", "robotics-overview", "app-protocols"]),
    ])


def mcu_articles():
    return _pack("microcontrollers", "Microcontrollers", [
        ("intro", "MCU vs SBC vs PLC", "Выбор", "Кто владеет ШИМ.",
         "MCU — детерминизм и GPIO. SBC — Linux. PLC — заводская экосистема. Роботу часто MCU+SBC.",
         "STM32 PID, Pi зрение, иногда Siemens для клетки безопасности.",
         "PWM @ MCU, SLAM @ SBC",
         ["один Pi на ток мотора 20 кГц без доказательства", "ПЛК на CV"],
         "Разные блоки HARDWARE. Связи между ними обязательны.",
         ["mcu-gpio", "linux-realtime", "robotics-control-split"]),
        ("gpio", "GPIO", "Периферия", "Направление, скорость, подтяжки.",
         "Пин — выход ШИМ/CS или вход ESTOP. После reset состояние опасно — задайте явно.",
         "ESTOP вход, STEP выход. Не оставляйте floating.",
         "pinMode analog: HAL GPIO_Init",
         ["плавающий ESTOP", "светодиод и STEP на одном пине «временно»"],
         "Таблица пинов — Documentation MCU. Связи к кнопке/драйверу.",
         ["electronics-pullup", "cpp-isr", "cpp-safety"]),
        ("adc", "АЦП", "Периферия", "Опора, шум, единицы.",
         "counts → вольты → амперы шунта. Фильтр. Не верьте одному сэмплу тока.",
         "Ток мотора, терморезистор, батарея.",
         "uint16_t raw; float i = (raw * vref / 4095) / r_shunt;",
         ["игнор vref", "земля АЦП рядом с силовым ключом без фильтра"],
         "Формулы в алгоритме MCU. Шунт — mechanical/electronics notes.",
         ["electronics-adc", "cpp-dma", "python-math"]),
        ("pwm", "PWM и драйверы", "Периферия", "Частота, dead-time.",
         "Частота выше слышимого или как просит драйвер. Dead-time чтобы не прострелить полумост.",
         "Колесо BLDC/DC. Документ драйвера.",
         "ARR, PSC, CCRx",
         ["слишком низкий PWM", "нет dead-time на полумосте"],
         "Связь MCU—Motor Controller: PWM/CAN. Частота в docs.",
         ["cpp-timers", "electronics-motor", "robotics-actuators"]),
        ("uart-mcu", "UART на MCU", "Периферия", "DMA vs IRQ.",
         "DMA circular + idle line — удобный кадр. Не poll в 1 кГц без нужды.",
         "Связь со шлюзом.",
         "USART + DMA RX",
         ["потерять байт без overrun handling", "разный baud"],
         "Протокол UART. Алгоритм DMA idle.",
         ["cpp-uart", "cpp-dma", "python-serial"]),
        ("timers-mcu", "Таймеры", "Периферия", "Несколько ролей.",
         "PWM, encoder quadrature, scheduler 1 кГц — разные таймеры предпочтительны.",
         "Энкодер на TIM в encoder mode.",
         "TIM2 encoder, TIM1 PWM, TIM6 tick",
         ["один таймер на PWM и tick с конфликтом ARR", "не тот AF пин"],
         "Вложенный холст MCU с блоками TIM.",
         ["cpp-timers", "robotics-odometry", "mcu-pwm"]),
        ("irq", "Прерывания на MCU", "Архитектура MCU", "Приоритеты NVIC.",
         "ESTOP выше UART. Не маскировать глобально надолго.",
         "См. C++ ISR.",
         "NVIC_SetPriority",
         ["низкий приоритет ESTOP", "всё в одном IRQ"],
         "Требование латентности.",
         ["cpp-isr", "cpp-safety", "mcu-gpio"]),
        ("clocks", "Тактирование и power", "Архитектура MCU", "RCC, PLL, sleep.",
         "Неверная частота — «случайный» baud. Sleep не для привода под нагрузкой без политики.",
         "Кварц, PLL до 168 МГц, шины APB для таймеров.",
         "SystemCoreClock",
         ["UART baud посчитан от другой частоты", "выключить таймер PWM в sleep"],
         "Hardware notes MCU: clock source.",
         ["electronics-psu", "cpp-hal", "mcu-boot"]),
        ("boot", "Загрузчик и прошивка", "Жизненный цикл", "DFU, dual bank, откат.",
         "Brick — риск. Dual bank или ROM bootloader. Версия в телеметрии.",
         "OTA через шлюз — процедура, не «запилить из MQTT любой бинарь».",
         "boot0, SWD, app offset",
         ["нет возможности прошить SWD после OTA-brick", "неподписанная прошивка из топика"],
         "Блок Tooling flash. version MCU.",
         ["python-subprocess", "git-tag", "cpp-gdb"]),
        ("rtos-mcu", "Нужен ли RTOS", "Архитектура MCU", "Цикл vs задачи.",
         "Простой робот — superloop 1 кГц. Сложный — FreeRTOS. Не RTOS ради резюме.",
         "Несколько шин + USB + PID — задачи. Один PID + UART — loop.",
         "while(1){ tick(); } vs tasks",
         ["RTOS и всё в одной задаче всё равно", "забытые стеки"],
         "Вложенный холст задач или один алгоритм loop.",
         ["cpp-freertos", "cpp-embedded", "mcu-irq"]),
        ("debug-mcu", "SWD, RTT, fault", "Жизненный цикл", "Стенд.",
         "Разъём SWD доступен в корпусе сервиса. HardFault_Handler логирует stacked PC.",
         "Не отлаживайте ток на весу без колодок.",
         "OpenOCD, ST-Link",
         ["оптимизация без символов в полевом расследовании", "питание отладчика и силовой земли"],
         "Стенд lab на холсте.",
         ["cpp-gdb", "electronics-ground", "mcu-boot"]),
        ("pick", "Как выбрать MCU", "Выбор", "FPU, CAN, таймеры, RAM.",
         "Нужен CAN+3 таймера encoder+FPU — не «самый дешёвый Arduino».",
         "Сопоставьте периферию с холстом связей.",
         "таблица: CAN, TIM, ADC, USB, RAM",
         ["выбор по цене модуля без карты пинов", "нехватка таймеров «потом»"],
         "Hardware catalog Raspberry/STM32/ESP. Пины в docs.",
         ["mcu-intro", "electronics-datasheet", "robotics-overview"]),
    ])


def electronics_articles():
    return _pack("electronics", "Electronics", [
        ("intro", "Электроника как часть модели", "Основы", "Не «черный ящик с проводами».",
         "Напряжения, земли, бюджет мощности, уровни GPIO — иначе протоколы в Canvas врут.",
         "24 В силовая, 5 В логика, 3.3 В MCU. DC-DC в BOM.",
         "P = I * V",
         ["питать мотор и MCU от одной неразвязанной линии без фильтра", "игнор datasheet"],
         "Hardware Data: voltage. PSU — блок. Связи питания можно описать notes, позже electrical kind.",
         ["electronics-psu", "electronics-ground", "electronics-datasheet"]),
        ("ohm", "Ток, напряжение, закон Ома", "Основы", "Шунты и падения.",
         "Длинный кабель 12 В к камере — падение. Считайте.",
         "LED, шунт 0.01 Ом, нагрев.",
         "V = I*R",
         ["тонкий провод на стартовый ток мотора", "измерять ток клещами как единственную правду без шунта в контуре"],
         "В notes актуатора: ток, провод, предохранитель.",
         ["electronics-motor", "electronics-psu", "electronics-intro"]),
        ("datasheet", "Как читать datasheet", "Практика", "Абсолютные максимумы ≠ рабочие.",
         "Режимы SPI, Vih/Vil, потребление, thermal. Ссылка в Documentation компонента.",
         "IMU, драйвер, MCU. Не копируйте интернет в приложение — храните URL и свои заметки.",
         "Vih min, Vil max, abs max Vin",
         ["питать 5 В пин 3.3 В MCU", "SPI 20 МГц при кабеле 30 см"],
         "Документы: Official + Datasheet URL + My notes.",
         ["electronics-levels", "cpp-spi", "app-docs"]),
        ("levels", "Уровни логики", "Практика", "3.3 vs 5 vs 24.",
         "Сдвиги уровней. ПЛК 24 В не втыкать в UART MCU.",
         "Датчик 5 В TTL → UART 3.3: делитель/трансивер.",
         "Vih, Vil, Voh",
         ["общий GND забыт при «сдвиге»", "оптопара без расчёта скорости"],
         "Связь UART заметки про трансивер. Блок level shifter при необходимости.",
         ["electronics-uart", "electronics-pullup", "mcu-gpio"]),
        ("pullup", "Подтяжки", "Практика", "I²C, кнопки, ESTOP.",
         "I²C без pull-up «иногда работает на столе». ESTOP: определите NC/NO и безопасное состояние обрыва.",
         "Кнопка ESTOP — аппаратно разрывает питание драйвера, логический пин — дубль.",
         "4.7k к 3.3 на SDA/SCL",
         ["внутренняя подтяжка MCU на длинной I²C", "ESTOP с подтяжкой, которая держит RUN при обрыве"],
         "Требование безопасного состояния обрыва. Схема в notes/файле.",
         ["cpp-i2c", "cpp-safety", "mcu-gpio"]),
        ("adc-el", "Цепи АЦП", "Сигналы", "RC, опора, дифференциальный шунт.",
         "Фильтр до ADC, Kelvin к шунту, не гонять силовой ток через землю АЦП.",
         "Ток колеса для защиты.",
         "RC 1k+100n как старт, потом посчитайте",
         ["длинная аналоговая рядом с PWM без экрана", "опора от шумного 3.3"],
         "Алгоритм ADC в MCU + notes цепи.",
         ["mcu-adc", "electronics-ground", "electronics-motor"]),
        ("uart-el", "UART/RS-485 физика", "Сигналы", "Трансиверы, земля, экран.",
         "TTL UART на метр — лотерея. RS-485 для шкафа. Общая земля или изолированный трансивер.",
         "ПЛК—шлюз, MCU—SBC в помехах мотора.",
         "A/B, termination 120",
         ["USB-UART висящий без земли к плате", "RS-485 без GND/reference"],
         "Протокол UART/Modbus RTU + физика в electronics notes.",
         ["protocols-uart", "protocols-modbus", "electronics-ground"]),
        ("can-el", "CAN физика", "Сигналы", "120 Ом, stub, экран.",
         "Два терминатора на концах. Не на каждом узле. Витая пара.",
         "Приводы в шине.",
         "CANH/CANL, 120Ω",
         ["терминатор на каждом серво", "питание трансивера откуда попало"],
         "Протокол CAN + notes шины.",
         ["cpp-can", "protocols-can", "electronics-ground"]),
        ("motor", "Силовая электроника привода", "Сила", "Драйвер, TVS, питание, тормоз.",
         "Стартовый ток, рекуперация, тормозной резистор. MCU не «качает мотор пином» кроме маленьких DC.",
         "Колесо, манипулятор. Блок Motor Controller.",
         "VMOT, nFAULT, nSLEEP",
         ["общий предохранитель логики и силы", "рекуперация без куда деть энергию"],
         "BOM: драйвер, предохранитель, конденсаторы. Связь MCU PWM/CAN.",
         ["mcu-pwm", "electronics-psu", "robotics-actuators"]),
        ("psu", "Питание", "Сила", "Бюджет, sequency, UVLO.",
         "Сначала логика, потом драйвера — или наоборот по datasheet. UVLO чтобы не дёргаться на просадке.",
         "АКБ 6S, DC-DC 5 В/3.3 В, 24 В приводы.",
         "I_budget = sum(I_max)*margin",
         ["питание Pi от того же узла, что стартует мотор, без ёмкости", "нет предохранителя"],
         "Блок PSU. Напряжения в Hardware Data всех потребителей.",
         ["electronics-ohm", "linux-disks", "electronics-intro"]),
        ("ground", "Заземление и EMC", "Сила", "Звезды, экраны, петли.",
         "Силовая земля отдельно от аналоговой, соединить в одной точке. Экраны камер.",
         "Сбросы MCU при старте мотора — классика петли.",
         "PGND vs AGND",
         ["земля через Ethernet shield и силовую одновременно без плана", "разорванная земля трансивера"],
         "Notes стойки/корпуса. Housing mechanical + electronics.",
         ["electronics-can", "networking-l2", "mcu-debug"]),
        ("esd", "ESD и защита входов", "Надёжность", "TVS, серии резисторы.",
         "Разъёмы, которые трогает оператор. USB, кнопки, UART наружу.",
         "Сервисный разъём прошивки.",
         "TVS + 22R series",
         ["голый GPIO на панель", "TVS с неверным напряжением"],
         "Документ разъёмов. Требование живучести.",
         ["electronics-levels", "mcu-gpio", "electronics-datasheet"]),
        ("proto", "Макет vs изделие", "Надёжность", "Навесное не едет в поле.",
         "Breadboard не для моторов. Изделие: PCB, крепёж, strain relief кабеля.",
         "Стенд ок. Робот — BOM и механика разъёмов.",
         "strain relief, connector P/N",
         ["макетная плата в корпусе робота", "кабель без петли компенсации изгиба"],
         "Mechanical assembly разъёма + part number в BOM.",
         ["robotics-mechanics", "app-bom", "electronics-motor"]),
    ])


def robotics_articles():
    return _pack("robotics", "Robotics", [
        ("overview", "Стек робота", "Карта", "Механика → сила → MCU → SBC → UI.",
         "Каждый слой — холст. Не пытайтесь одним прямоугольником «Robot».",
         "Учебный шаблон «Робот» в Canvas — старт, его раскладывают вложенностью.",
         "layers: mech, power, mcu, sbc, cloud",
         ["один блок Robot без внутренностей", "зрение внутри PID MCU"],
         "Создайте проект из шаблона Робот и провалитесь в контроллер.",
         ["robotics-control-split", "app-nested", "sw-layers"]),
        ("control-split", "Где какой контур", "Управление", "Частоты и ответственность.",
         "Ток 10–20 кГц MCU. Скорость 1 кГц MCU. Поза/план 10–50 Гц SBC. Миссия 1 Гц UI.",
         "Нарушение — джиттер и опасность.",
         "loop rates table",
         ["планировщик на MCU", "ток на Python"],
         "Алгоритмы на соответствующих блоках. Связи setpoint/feedback.",
         ["python-pid", "cpp-pid", "linux-realtime"]),
        ("kinematics", "Кинематика", "Движение", "Позы и скорости без сил.",
         "Дифф. база: vx, wz → omega колёс. Манипулятор: FK/IK. Совпадение с механической цепью холста.",
         "Drive System / Left Wheel — те же имена в коде.",
         "omega_l = (vx - wz*L/2)/r",
         ["перепутать радиус и диаметр", "frame без имени"],
         "Mechanical nested canvas = цепь преобразований.",
         ["cpp-eigen", "python-math", "robotics-frames"]),
        ("dynamics", "Динамика (практика)", "Движение", "Инерция, не всегда полный Лагранж.",
         "Ограничения ускорения, нагрузка, наклон. Feedforward + PID часто хватает мобильному роботу.",
         "Клетка, уклон, манипулятор с грузом.",
         "a_max, alpha_max",
         ["игнор проскальзывания как «динамика потом»", "модель, которую не идентифицировали"],
         "Ограничения в конфиге и requirements.",
         ["robotics-pid", "robotics-actuators", "python-config"]),
        ("pid", "ПИД в системе", "Управление", "Каскад, единицы, anti-windup.",
         "Каскад ток→скорость→позиция. Не один PID на «всё». Симуляция Python, бой C++ — одни имена коэффициентов.",
         "Колесо, шарнир, температура — разные контуры.",
         "Kp Ki Kd, Ilim, Umax",
         ["настройка на столе без нагрузки", "интегратор при насыщении ШИМ"],
         "Алгоритм блока привода. Коэффициенты в конфиге.",
         ["python-pid", "cpp-pid", "robotics-control-split"]),
        ("sensors", "Сенсоры", "Ощущение", "Модель ошибки, не «есть лидар».",
         "Частота, шум, слепые зоны, калибровка. Камера не замена концевику безопасности.",
         "IMU, энкодер, лидар, ток.",
         "rate, range, frame, calib file",
         ["один сенсор на безопасность и SLAM без redundancy", "нет timeout кадра"],
         "Блоки Sensor/Camera/Lidar. Docs datasheet. data_flow частоты.",
         ["python-opencv", "robotics-frames", "cpp-watchdog"]),
        ("actuators", "Приводы", "Действие", "Мотор, редуктор, драйвер — три сущности.",
         "Механика редуктора влияет на inertia и backlash. В Canvas: Motor, Gearbox, Wheel.",
         "Дифф. база: два сборки колеса.",
         "tau, reduction, backlash",
         ["модель без люфта, а люфт есть", "драйвер без nFAULT в архитектуре"],
         "Вложенный mechanical canvas. BOM part numbers.",
         ["electronics-motor", "app-mech", "robotics-kinematics"]),
        ("frames", "Системы координат", "Ощущение", "Имена кадров обязательны.",
         "base_link, wheel_left, lidar, camera. Без TF каша облаков.",
         "Документ frames = механическая иерархия.",
         "T_base_lidar",
         ["два «вперёд» у камеры и базы", "калибровка в голове"],
         "Имена блоков механики = имена кадров.",
         ["robotics-kinematics", "python-numpy", "robotics-calibration"]),
        ("odometry", "Одометрия", "Локализация", "Интеграция колёс и IMU.",
         "Скольжение убивает. Fuse осторожно. Stamp и dt monotonic.",
         "Дифф. база лабораторная vs склад с пылью.",
         "x += v*cos(yaw)*dt",
         ["интегрировать yaw гироскопа без bias", "смешать единицы ticks"],
         "Алгоритм Localization. Входы энкодеры/IMU.",
         ["python-math", "cpp-pid", "robotics-slam"]),
        ("slam", "SLAM и карты", "Локализация", "Отдельный тяжёлый компонент.",
         "Не на MCU. Карта — артефакт версии. Потеря лидара — поведение fail-safe.",
         "Склад, навигация.",
         "map.pgm + yaml",
         ["SLAM  в том же процессе, что UART 1 кГц, без приоритетов", "карта без версии"],
         "Блок SLAM. Файлы карты — attached/runtime path. Связь Lidar UDP.",
         ["python-numpy", "networking-udp", "robotics-nav"]),
        ("nav", "Планирование и следование", "Навигация", "Глобальный план vs локальный.",
         "Глобальный путь 1 Гц, локальный 10 Гц, контроль 1 кГц. Препятствие — локальный.",
         "Доехать до дока.",
         "global / local / control",
         ["глобальный планировщик дёргает PWM", "нет поведения «стоп если нет плана»"],
         "Три блока или вложенный холст Nav. Связи setpoint.",
         ["robotics-control-split", "python-state-machine", "robotics-safety"]),
        ("safety", "Безопасность робота", "Безопасность", "Слои.",
         "Клетка, ESTOP, ограничение скорости, watchdogs, безопасные состояния ПО. Не один if.",
         "Выставка vs цех — разные must requirements.",
         "E-stop, light curtain, software limits",
         ["софт-стоп вместо грибка", "тест безопасности только в симе"],
         "Requirements must. Связи GPIO ESTOP. Алгоритм FAULT.",
         ["cpp-safety", "electronics-pullup", "app-requirements"]),
        ("calibration", "Калибровка", "Эксплуатация", "Процедура, файл, версия.",
         "Камера, IMU bias, колесная база. Дата и robot_id. Не «подкрутили Kp навсегда».",
         "После замены колеса — процедура. Tooling блок.",
         "calib.yaml version",
         ["калибровка в коде константой", "файл без robot serial"],
         "Attached notes + runtime path. Requirement после обслуживания.",
         ["python-config", "git-lfs", "robotics-frames"]),
        ("sim", "Симуляция", "Эксплуатация", "Контракты те же.",
         "Fake MCU, gazebo, свой kinematic sim. Те же протоколы и автоматы. Иначе сим врёт.",
         "CI на парсер и автомат. Ночной прогон навигации.",
         "profile=sim",
         ["другой протокол в симе «так проще»", "сим без ESTOP-веток"],
         "Вложенный стенд Sim. Docker profile.",
         ["docker-sim", "python-protocols-abc", "python-testing"]),
        ("mechanics", "Механика в архитектуре", "Механика", "Сборка как сущность.",
         "System/subsystem/assembly/part. STL на детали. BOM из модели.",
         "Drive / Left Wheel / Gearbox / Shaft / Bearing.",
         "quantity, material, mass",
         ["картинка вместо вложенного холста", "STL без версии"],
         "Раздел Механика, double-click, BOM, файлы STL.",
         ["app-mech", "app-stl", "app-bom"]),
    ])


def sw_articles():
    return _pack("software-architecture", "Software Architecture", [
        ("overview", "Архитектура ПО робота", "Основы", "Компоненты и контракты.",
         "Софт — граф ответственности. Canvas — этот граф. Код не должен иметь тайных связей.",
         "Backend, MCU firmware, UI, tools.",
         "components + connections = architecture",
         ["shared util, который импортируют все", "бог-процесс"],
         "Системный холст + вложенные. Правило: импорт = ребро.",
         ["python-architecture", "sw-layers", "app-canvas"]),
        ("layers", "Слои", "Основы", "drivers / domain / api.",
         "Domain не знает FastAPI. Drivers не знают миссии. API переводит HTTP в команды домена.",
         "Python пакеты = слои. C++ app vs hal.",
         "api → supervisor → drivers",
         ["драйвер UART вызывает HTTP", "UI в прошивке"],
         "Вложенный холст Backend.",
         ["python-modules", "cpp-hal", "sw-ports"]),
        ("ports", "Порты и адаптеры", "Основы", "Hexagonal без религии.",
         "Порт Bus.send. Адаптеры: SocketCAN, Fake, Serial. Тесты на fake.",
         "Смена транспорта не ломает автомат.",
         "interface Bus",
         ["адаптер, который знает про UI", "10 портов на каждый чих"],
         "Интерфейсы компонента = порты.",
         ["python-protocols-abc", "sw-layers", "python-testing"]),
        ("events", "События vs запросы", "Связи", "Когда брокер, когда RPC.",
         "Телеметрия — события. Старт миссии — команда с ответом. ESTOP — не «событие в лучшем усилии» как единственный путь.",
         "MQTT imu, HTTP start, GPIO estop.",
         "cmd vs telemetry vs safety",
         ["все через события «реактивно»", "команда без идемпотентности"],
         "Тип связи connection vs data_flow. Reliability в инспекторе.",
         ["protocols-mqtt", "protocols-http", "cpp-safety"]),
        ("sync", "Синхронность и очереди", "Связи", "Границы потоков.",
         "Каждый I/O — очередь и политика drop. Документируйте.",
         "UART thread → q → supervisor.",
         "queue maxsize, drop-old | block | fault",
         ["общий dict без лока", "безлимит очередь кадров"],
         "data_flow notes: частота и политика.",
         ["python-queues", "cpp-queues", "sw-events"]),
        ("api-design", "Дизайн API", "Контракты", "Команды домена, не «набор GET».",
         "Имена как у автомата. Коды ошибок как FAULT reasons. Версия API.",
         "POST /missions/{id}/start",
         "OpenAPI = документация блока API",
         ["CRUD на pwm", "разные имена режима в UI и MCU"],
         "Поле API компонента. Состояния совпадают с algorithm.",
         ["python-fastapi", "python-enums", "sw-errors"]),
        ("errors", "Ошибки и отказы", "Контракты", "Классы отказов.",
         "Транзиент (retry), постоянный (FAULT), безопасность (ESTOP). Не один catch.",
         "CRC vs отсутствие лидара vs грибок.",
         "retry | degrade | stop | halt-power",
         ["retry на ESTOP", "degrade без индикации оператору"],
         "failure_modes каждого блока. Requirements.",
         ["python-exceptions", "cpp-expected", "robotics-safety"]),
        ("observe", "Наблюдаемость", "Эксплуатация", "Логи, метрики, трассы.",
         "correlation id миссии в логах шлюза и MCU seq. Иначе инцидент не собрать.",
         "journald + MQTT fault + SQL events.",
         "mission_id, seq, mode",
         ["метрики без меток робота", "PII в логах камеры"],
         "Документ observability у системы.",
         ["python-logging", "linux-journalctl", "sql-intro"]),
        ("deploy", "Поставка", "Эксплуатация", "Пин версий набора.",
         "Прошивка + шлюз + UI + схема БД. Матрица совместимости протоколов.",
         "Релиз v1.4: firmware 1.4.0, svc 1.4.1, uart proto v2.",
         "compatibility matrix",
         ["обновили только UI", "нет отката"],
         "version на блоках. tag git. docker digest.",
         ["git-tag", "docker-ci", "protocols-versioning"]),
        ("embed-split", "Граница embedded/Linux", "Практика", "Самое важное ребро.",
         "Документируйте кадр, частоты, кто watchdog. Это сердце архитектуры робота.",
         "Связь MCU—Gateway.",
         "frame, hz, watchdog, estop independent",
         ["скрытый второй канал «отладки», который может задать RUN", "разные endian без записи"],
         "Протокол Custom/UART/CAN между HARDWARE и SOFTWARE.",
         ["protocols-choose", "cpp-struct", "python-struct"]),
        ("integration", "Интеграция с заводом/IT", "Практика", "OPC UA, MES, люди.",
         "Шлюз наружу, не прошивка. ACL. Имена из Canvas совпадают с тегами SCADA если можете.",
         "Цех хочет статус робота.",
         "OT vs IT DMZ",
         ["дать MES писать PWM", "разные имена статусов"],
         "Блок External Service. Протокол OPC UA/HTTP.",
         ["protocols-opcua", "linux-firewall", "sw-api-design"]),
        ("canvas-map", "Как вести Canvas и код вместе", "Практика", "Правило синхронизации.",
         "Новый импорт/топик/таблица → сразу ребро или сущность. PR без обновления архитектуры неполный.",
         "Ревью: diff кода и diff модели.",
         "code change ⇒ model change",
         ["архитектура «потом нарисуем»", "холст для презентации, код другой"],
         "Экспорт AI тогда помогает, а не врёт.",
         ["app-export-ai", "python-architecture", "git-commit"]),
    ])


def app_articles():
    return _pack("app", "Architecture Canvas", [
        ("create", "Создание проекта", "Старт", "Шаблоны заполняют модель, не картинку.",
         "Имя, шаблон (Пустой, Веб, Робот, IoT, Промка). Сразу появляются компоненты, протоколы, связи.",
         "Для робота берите шаблон Робот и наращивайте механику/БД.",
         "Главный экран → Создать проект",
         ["пустой холст и забыть протоколы", "английский UI — интерфейс русский, имена протоколов технические"],
         "Это стартовая точка справочника приложения.",
         ["app-canvas", "app-templates", "robotics-overview"]),
        ("templates", "Шаблоны", "Старт", "Свои шаблоны — снимок модели.",
         "Сохраните проект как шаблон в Экспорте. Это JSON модели, не скрин.",
         "Команда роботов одного типа.",
         "Экспорт → Сохранить как шаблон",
         ["шаблон без вложенных холстов, если они были нужны", "секреты в шаблоне"],
         "Шаблоны на главной.",
         ["app-create", "app-export-json", "app-versions"]),
        ("canvas", "Холст", "Холст", "Бесконечный граф сущностей.",
         "Перетаскивание из библиотеки, зум, сетка, мини-карта. Двойной клик — вложенность.",
         "Раскладка не семантика: координаты не уходят в AI-экспорт по смыслу модели.",
         "DnD из библиотеки, Delete, Ctrl+Z",
         ["считать холст Visio", "удалять блок и оставлять «висящие» ожидания в голове — связи удалятся, документы проверьте"],
         "Раздел Архитектура.",
         ["app-blocks", "app-links", "app-nested"]),
        ("blocks", "Архитектурные блоки", "Холст", "Тип + категория + семантика.",
         "ПО, железо, данные, сеть, механика — разные тон и иконка. Это ComponentType.",
         "Python Backend, STM32, PostgreSQL, Колесо — разные категории.",
         "Инспектор → Обзор: тип, технология, статус",
         ["все блоки «прочее»", "механика картинкой без полей"],
         "Библиотека слева. Категории в инспекторе.",
         ["app-library", "app-docs", "app-mech"]),
        ("library", "Библиотека компонентов", "Холст", "Заготовки, не идолы.",
         "Перетащите Python-бэкенд, MQTT, таблицу, механическую систему. Потом переименуйте под проект.",
         "На холсте БД библиотека фильтруется к таблицам.",
         "Двойной клик в библиотеке = добавить",
         ["не искать — библиотека длинная, есть поиск", "забыть категорию MECHANICS"],
         "Поиск в библиотеке. Режимы Механика/БД фильтруют.",
         ["app-blocks", "app-database", "app-mech"]),
        ("links", "Связи", "Холст", "Протокол, направление, данные.",
         "Соедините хендлы. В инспекторе: протокол, пример payload, частота, надёжность, цвет.",
         "PLC — Modbus TCP → Python. Подпись на линии.",
         "Инспектор связи",
         ["связь без протокола «чтобы было»", "ESTOP через MQTT без GPIO-ребра"],
         "Цвет по типу протокола, override вручную.",
         ["app-protocols", "protocols-intro", "app-export-ai"]),
        ("protocols", "Каталог протоколов", "Модель", "Сущность Protocol.",
         "Раздел Протоколы: версия, транспорт, CRC, цвет. Связь ссылается именем.",
         "Добавьте свой кадр UART.",
         "Навигация → Протоколы",
         ["только цвет без message_structure", "две записи HTTP с разным смыслом без описания"],
         "Цвет по умолчанию из каталога.",
         ["protocols-intro", "app-links", "python-struct"]),
        ("nested", "Вложенные архитектуры", "Модель", "Проваливание внутрь блока.",
         "Двойной клик / инспектор «Вложенность». Хлебные крошки сверху. Механика тем же механизмом.",
         "Robot / Mechanical System / Drive / Left Wheel.",
         "Открыть внутреннюю архитектуру",
         ["копировать систему рядом вместо вложенности", "забыть выйти крошками"],
         "kind mechanical/database выставляется по категории при создании вложенности.",
         ["app-mech", "app-canvas", "sw-layers"]),
        ("inspector", "Инспектор", "Модель", "Семантика выбранного.",
         "Вкладки: обзор, документация, алгоритм, вложенность, требования, механика, таблица, файлы.",
         "Заполняйте не координаты — смысл.",
         "Выделите блок",
         ["пустые все поля и ждать чудес от AI-экспорта", "документация только в чате"],
         "Правая панель на холсте.",
         ["app-docs", "app-algorithms", "app-files"]),
        ("docs", "Документация компонента", "Модель", "Markdown, ссылки, datasheet.",
         "Вкладка Документация: назначение, входы/выходы + список docs (ссылка на raspberry.com, свои заметки).",
         "Raspberry Pi 5: Official + GPIO notes + My notes.",
         "Добавить ссылку / Markdown / Datasheet",
         ["копировать весь интернет в поле", "URL без названия"],
         "Документы привязаны к component_id/protocol_id.",
         ["app-inspector", "electronics-datasheet", "app-export-ai"]),
        ("algorithms", "Алгоритмы", "Модель", "Шаги, состояния, переходы.",
         "Не замена IDE. Контракт поведения: PID шаги, автомат режимов. Совпадайте с кодом.",
         "MCU tick, супервизор режимов.",
         "Вкладка Алгоритм → создать",
         ["алгоритм «и всё» одним шагом", "состояния не как в прошивке"],
         "Раздел Алгоритмы и вкладка блока. Экспорт AI опционально включает их.",
         ["python-state-machine", "cpp-state-machine", "app-export-ai"]),
        ("requirements", "Требования", "Модель", "REQ-id и связи с блоками.",
         "Must для ESTOP. Привязка к компонентам. Тесты именуйте REQ.",
         "«Движение невозможно при разомкнутом контуре».",
         "Раздел Требования, кнопка связать в инспекторе",
         ["требования в слайдах, не в модели", "все should"],
         "Экспорт включает requirements по флажку.",
         ["robotics-safety", "python-testing", "app-export-ai"]),
        ("database", "ER и SQL", "Данные", "Таблицы — компоненты.",
         "Раздел База данных создаёт architecture kind=database. Колонки, PK, связь 1–N ставит FK. SQL PostgreSQL/MySQL/SQLite.",
         "users/projects учебный пример.",
         "Показать SQL → скачать .sql",
         ["ER в draw.io отдельно", "N–N без понимания junction"],
         "Инспектор таблицы. Экспорт SQL.",
         ["sql-er", "sql-keys", "app-export-ai"]),
        ("mech", "Механическая архитектура", "Механика", "Те же вложенные холсты.",
         "Раздел Механика фильтрует библиотеку. Поля материала, массы, qty. Double-click в сборку.",
         "Drive System → Left Wheel Assembly.",
         "Вкладка Механика в инспекторе",
         ["сборка без деталей внутри", "qty=1 при 4 колёсах без мысли"],
         "BOM собирается из HARDWARE+MECHANICS.",
         ["robotics-mechanics", "app-nested", "app-bom"]),
        ("stl", "STL и 3D", "Механика", "Файлы на детали, preview STL.",
         "Вкладка Файлы: STL/STEP/OBJ. Просмотр STL (вращение/зум). STEP пока как вложение.",
         "wheel_v1.stl, wheel_v2.stl версии.",
         "Загрузить → Просмотр STL",
         ["хранить CAD только на личном диске без ссылки в модели", "ожидать STEP-preview в MVP"],
         "AttachedFile.component_id = деталь.",
         ["app-files", "app-mech", "git-lfs"]),
        ("files", "Файлы и 3D-печать", "Механика", "Метаданные и печать.",
         "Имя, тип, размер, дата, version. Опционально nozzle, layer, infill во вкладке механики.",
         "Кронштейн печати.",
         "3D Printing fields",
         ["печать без материала в BOM", "версия файла не совпадает с version детали"],
         "PrintSettings в MechanicalData.",
         ["app-stl", "app-bom", "electronics-proto"]),
        ("bom", "BOM", "Механика", "Инженерный список, не склад.",
         "Раздел BOM: имя, категория, производитель, артикул, qty, заметки. Берётся из модели.",
         "Закупка прототипа.",
         "Навигация → BOM",
         ["вести Excel параллельно как истину", "нет part number у критичных деталей"],
         "Экспорт JSON содержит bom. AI — в составе полного экспорта.",
         ["app-mech", "electronics-motor", "app-export-json"]),
        ("export-json", "JSON-модель", "Экспорт", "Канонический снимок.",
         "Семантика компонентов, связей, таблиц, механики. Можно импортировать.",
         "Обмен между машинами, git рядом с кодом.",
         "Экспорт → Скачать JSON / Импорт",
         ["править координаты вручную в JSON без нужды", "импорт как «merge» — сейчас новый проект-копия"],
         "format architecture-canvas.",
         ["app-export-md", "app-versions", "sw-canvas-map"]),
        ("export-md", "Markdown-экспорт", "Экспорт", "Читаемый отчёт.",
         "Компоненты, связи, БД, механика, требования. Для PR и людей.",
         "Описание системы заказчику.",
         "Скачать Markdown",
         ["ждать красивый PDF-бренд", "пусто, если не заполняли инспектор"],
         "Раздел Экспорт.",
         ["app-export-json", "app-docs", "app-export-ai"]),
        ("export-ai", "Экспорт для AI", "Экспорт", "Объём и scope.",
         "Не весь мир в промпт. Scope: всё / текущий холст / выбор / БД / механика / алгоритмы. Флажки документации и SQL.",
         "Просите дописать парсер UART — экспортируйте MCU+шлюз+протокол, не BOM корпуса.",
         "Экспорт для AI → объём → сформировать",
         ["include full markdown всех datasheet", "координаты как истина"],
         "Промпт строится из семантической модели.",
         ["sw-canvas-map", "app-docs", "sql-er"]),
        ("versions", "Снимки версий", "Экспорт", "Метки модели.",
         "Сохранить снимок архитектуры. Это не git, но рядом с git tag удобно.",
         "Перед ломающим изменение протокола.",
         "Экспорт → Сохранить снимок версии",
         ["100 снимков без имён", "считать это CAD PDM"],
         "current_version_label в шапке.",
         ["git-tag", "app-export-json", "protocols-versioning"]),
        ("shortcuts", "Клавиши и темы", "Приложение", "Скорость работы.",
         "Ctrl+S сохранение, Ctrl+Z/Y история, Ctrl+K поиск, Delete, светлая/тёмная тема. Автосохранение.",
         "Цвета протоколов читаемы в обеих темах.",
         "Ctrl+K поиск сущностей",
         ["набрать в поле и нажать Delete — удалит блок, если фокус не в input — наоборот, в input не удалит граф"],
         "Верхняя панель.",
         ["app-canvas", "app-inspector", "app-create"]),
    ])


def rest_articles() -> list[str]:
    return (
        linux_articles() + git_articles() + bash_articles() + sql_articles()
        + docker_articles() + databases_articles() + networking_articles()
        + protocols_articles() + mcu_articles() + electronics_articles()
        + robotics_articles() + sw_articles() + app_articles()
    )


