from __future__ import annotations

from app.domain.schema import ComponentTypeDef, HardwareComponent, Protocol


BUILTIN_TYPES: list[ComponentTypeDef] = [
    ComponentTypeDef(id="application", category="SOFTWARE", name="Приложение", icon="app"),
    ComponentTypeDef(id="service", category="SOFTWARE", name="Сервис", icon="service"),
    ComponentTypeDef(id="backend", category="SOFTWARE", name="Бэкенд", icon="server"),
    ComponentTypeDef(id="frontend", category="SOFTWARE", name="Фронтенд", icon="layout"),
    ComponentTypeDef(id="library", category="SOFTWARE", name="Библиотека", icon="book"),
    ComponentTypeDef(id="module", category="SOFTWARE", name="Модуль", icon="puzzle"),
    ComponentTypeDef(id="api", category="SOFTWARE", name="API", icon="api"),
    ComponentTypeDef(id="mcu", category="HARDWARE", name="MCU", icon="chip"),
    ComponentTypeDef(id="cpu", category="HARDWARE", name="CPU", icon="cpu"),
    ComponentTypeDef(id="sbc", category="HARDWARE", name="SBC", icon="board"),
    ComponentTypeDef(id="plc", category="HARDWARE", name="ПЛК", icon="factory"),
    ComponentTypeDef(id="sensor", category="HARDWARE", name="Датчик", icon="sensor"),
    ComponentTypeDef(id="actuator", category="HARDWARE", name="Исполнитель", icon="motor"),
    ComponentTypeDef(id="motor-controller", category="HARDWARE", name="Контроллер двигателя", icon="motor"),
    ComponentTypeDef(id="camera", category="HARDWARE", name="Камера", icon="camera"),
    ComponentTypeDef(id="lidar", category="HARDWARE", name="LiDAR", icon="radar"),
    ComponentTypeDef(id="network-device", category="HARDWARE", name="Сетевое устройство", icon="network"),
    ComponentTypeDef(id="custom-hardware", category="HARDWARE", name="Своё железо", icon="box"),
    ComponentTypeDef(id="postgresql", category="DATA", name="PostgreSQL", icon="db"),
    ComponentTypeDef(id="mysql", category="DATA", name="MySQL", icon="db"),
    ComponentTypeDef(id="sqlite", category="DATA", name="SQLite", icon="db"),
    ComponentTypeDef(id="redis", category="DATA", name="Redis", icon="cache"),
    ComponentTypeDef(id="mongodb", category="DATA", name="MongoDB", icon="db"),
    ComponentTypeDef(id="file-storage", category="DATA", name="Файловое хранилище", icon="folder"),
    ComponentTypeDef(id="message-queue", category="DATA", name="Очередь сообщений", icon="queue"),
    ComponentTypeDef(id="custom-database", category="DATA", name="Своя БД", icon="db"),
    ComponentTypeDef(id="http", category="PROTOCOL", name="HTTP", icon="protocol"),
    ComponentTypeDef(id="https", category="PROTOCOL", name="HTTPS", icon="protocol"),
    ComponentTypeDef(id="tcp", category="PROTOCOL", name="TCP", icon="protocol"),
    ComponentTypeDef(id="udp", category="PROTOCOL", name="UDP", icon="protocol"),
    ComponentTypeDef(id="mqtt", category="PROTOCOL", name="MQTT", icon="protocol"),
    ComponentTypeDef(id="websocket", category="PROTOCOL", name="WebSocket", icon="protocol"),
    ComponentTypeDef(id="modbus-tcp", category="PROTOCOL", name="Modbus TCP", icon="protocol"),
    ComponentTypeDef(id="modbus-rtu", category="PROTOCOL", name="Modbus RTU", icon="protocol"),
    ComponentTypeDef(id="can", category="PROTOCOL", name="CAN", icon="protocol"),
    ComponentTypeDef(id="opc-ua", category="PROTOCOL", name="OPC UA", icon="protocol"),
    ComponentTypeDef(id="opc-da", category="PROTOCOL", name="OPC DA", icon="protocol"),
    ComponentTypeDef(id="serial", category="PROTOCOL", name="Serial", icon="protocol"),
    ComponentTypeDef(id="custom-protocol", category="PROTOCOL", name="Свой протокол", icon="protocol"),
    ComponentTypeDef(id="cloud", category="OTHER", name="Облако", icon="cloud"),
    ComponentTypeDef(id="external-service", category="OTHER", name="Внешний сервис", icon="globe"),
    ComponentTypeDef(id="user", category="OTHER", name="Пользователь", icon="user"),
    ComponentTypeDef(id="custom-component", category="OTHER", name="Свой компонент", icon="box"),
]


BUILTIN_PROTOCOLS: list[Protocol] = [
    Protocol(id="proto-http", name="HTTP", version="1.1", transport="TCP", port="80", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="Протокол передачи гипертекста", built_in=True),
    Protocol(id="proto-https", name="HTTPS", version="1.1", transport="TCP/TLS", port="443", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="HTTP поверх TLS", built_in=True),
    Protocol(id="proto-tcp", name="TCP", version="1.0", transport="TCP", port="", direction="bidirectional", data_format="Binary", description="Протокол управления передачей", built_in=True),
    Protocol(id="proto-udp", name="UDP", version="1.0", transport="UDP", port="", direction="unidirectional", data_format="Binary", description="Протокол пользовательских датаграмм", built_in=True),
    Protocol(id="proto-mqtt", name="MQTT", version="5.0", transport="TCP", port="1883", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="Лёгкий протокол публикации и подписки", message_structure="topic + payload", timeout="30 с", retry="экспоненциальный backoff", built_in=True),
    Protocol(id="proto-ws", name="WebSocket", version="13", transport="TCP", port="80/443", direction="bidirectional", data_format="JSON", description="Двусторонний канал браузер/сервер", built_in=True),
    Protocol(id="proto-modbus-tcp", name="Modbus TCP", version="1.0", transport="TCP", port="502", direction="bidirectional", data_format="Registers", description="Промышленный Modbus поверх TCP", timeout="1 с", retry="3", crc="контрольная сумма TCP", built_in=True),
    Protocol(id="proto-modbus-rtu", name="Modbus RTU", version="1.0", transport="Serial", port="", direction="bidirectional", data_format="Registers", crc="CRC16", built_in=True),
    Protocol(id="proto-can", name="CAN", version="2.0", transport="CAN bus", port="", direction="bidirectional", data_format="Frames", description="Шина Controller Area Network", crc="CRC15", built_in=True),
    Protocol(id="proto-opcua", name="OPC UA", version="1.04", transport="TCP", port="4840", direction="bidirectional", data_format="Nodeset", built_in=True),
    Protocol(id="proto-opcda", name="OPC DA", version="3.0", transport="COM/DCOM", port="", direction="bidirectional", data_format="Items", built_in=True),
    Protocol(id="proto-serial", name="Serial", version="1.0", transport="UART", port="", direction="bidirectional", data_format="Bytes", encoding="ASCII", built_in=True),
]


BUILTIN_HARDWARE: list[HardwareComponent] = [
    HardwareComponent(id="hw-stm32", name="STM32", manufacturer="STMicroelectronics", model="STM32F4", cpu="ARM Cortex-M4", ram="192KB", interfaces="UART, SPI, I2C, CAN, GPIO", voltage="3.3V", protocols="CAN, UART, Modbus", os="Bare-metal / FreeRTOS", category="MCU", built_in=True),
    HardwareComponent(id="hw-esp32", name="ESP32", manufacturer="Espressif", model="ESP32-WROOM", cpu="Xtensa LX6 dual-core", ram="520KB", interfaces="Wi-Fi, BLE, UART, SPI, I2C", voltage="3.3V", protocols="MQTT, HTTP, UART", os="ESP-IDF / Arduino", category="MCU", built_in=True),
    HardwareComponent(id="hw-rpi", name="Raspberry Pi", manufacturer="Raspberry Pi Ltd", model="Raspberry Pi 5", cpu="ARM Cortex-A76", ram="8GB", interfaces="Ethernet, USB, CSI, GPIO, HDMI", voltage="5V", protocols="HTTP, MQTT, WebSocket", os="Raspberry Pi OS", category="SBC", built_in=True),
    HardwareComponent(id="hw-arduino", name="Arduino", manufacturer="Arduino", model="Uno / Mega", cpu="ATmega328P", ram="2KB", interfaces="UART, SPI, I2C, GPIO", voltage="5V", protocols="Serial", os="Arduino", category="MCU", built_in=True),
    HardwareComponent(id="hw-siemens-plc", name="Siemens PLC", manufacturer="Siemens", model="S7-1500", cpu="ПЛК CPU", ram="", interfaces="PROFINET, Ethernet", voltage="24V", protocols="OPC UA, Modbus TCP, PROFINET", os="TIA Portal runtime", category="ПЛК", built_in=True),
    HardwareComponent(id="hw-ipc", name="Промышленный ПК", manufacturer="универсальный", model="IPC", cpu="x86_64", ram="16GB", interfaces="Ethernet, USB, PCIe", voltage="24V", protocols="OPC UA, MQTT, HTTP", os="Linux / Windows IoT", category="CPU", built_in=True),
    HardwareComponent(id="hw-sensor", name="Датчик", manufacturer="универсальный", model="", interfaces="I2C / Analog / UART", voltage="3.3V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-motor", name="Двигатель", manufacturer="универсальный", model="", interfaces="PWM / CAN", voltage="24V", category="Исполнитель", built_in=True),
    HardwareComponent(id="hw-servo", name="Сервопривод", manufacturer="универсальный", model="", interfaces="PWM / RS485", voltage="24V", category="Исполнитель", built_in=True),
    HardwareComponent(id="hw-encoder", name="Энкодер", manufacturer="универсальный", model="", interfaces="A/B/Z / SSI", voltage="5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-camera", name="Камера", manufacturer="универсальный", model="", interfaces="CSI / USB / GigE", voltage="5V", protocols="RTSP / USB Video", category="Камера", built_in=True),
    HardwareComponent(id="hw-lidar", name="LiDAR", manufacturer="универсальный", model="", interfaces="Ethernet / UART", voltage="12V", protocols="UDP point cloud", category="LiDAR", built_in=True),
    HardwareComponent(id="hw-motor-ctrl", name="Контроллер двигателя", manufacturer="универсальный", model="", interfaces="CAN / PWM", voltage="24-48V", protocols="CAN", category="Контроллер двигателя", built_in=True),
]


LIBRARY_PRESETS = [
    {"name": "PostgreSQL", "type": "PostgreSQL", "category": "DATA", "icon": "db", "technology": "PostgreSQL"},
    {"name": "Redis", "type": "Redis", "category": "DATA", "icon": "cache", "technology": "Redis"},
    {"name": "MQTT", "type": "MQTT", "category": "PROTOCOL", "icon": "protocol", "technology": "MQTT", "protocol_id": "proto-mqtt"},
    {"name": "Raspberry Pi", "type": "SBC", "category": "HARDWARE", "icon": "board", "technology": "Linux", "hardware_id": "hw-rpi"},
    {"name": "STM32", "type": "MCU", "category": "HARDWARE", "icon": "chip", "technology": "C/C++", "hardware_id": "hw-stm32"},
    {"name": "ESP32", "type": "MCU", "category": "HARDWARE", "icon": "chip", "technology": "ESP-IDF", "hardware_id": "hw-esp32"},
    {"name": "Python-бэкенд", "type": "Бэкенд", "category": "SOFTWARE", "icon": "server", "technology": "Python"},
    {"name": "React-фронтенд", "type": "Фронтенд", "category": "SOFTWARE", "icon": "layout", "technology": "React"},
    {"name": "Docker", "type": "Модуль", "category": "SOFTWARE", "icon": "box", "technology": "Docker"},
    {"name": "Камера", "type": "Камера", "category": "HARDWARE", "icon": "camera", "hardware_id": "hw-camera"},
    {"name": "LiDAR", "type": "LiDAR", "category": "HARDWARE", "icon": "radar", "hardware_id": "hw-lidar"},
    {"name": "Контроллер двигателя", "type": "Контроллер двигателя", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor-ctrl"},
    {"name": "WebSocket", "type": "WebSocket", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-ws"},
    {"name": "Modbus TCP", "type": "Modbus TCP", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-modbus-tcp"},
    {"name": "CAN", "type": "CAN", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-can"},
    {"name": "ПЛК", "type": "ПЛК", "category": "HARDWARE", "icon": "factory", "hardware_id": "hw-siemens-plc"},
]
