from __future__ import annotations

from app.domain.schema import ComponentTypeDef, HardwareComponent, Protocol, color_for_protocol


BUILTIN_TYPES: list[ComponentTypeDef] = [
    ComponentTypeDef(id="application", category="SOFTWARE", name="Приложение", icon="app"),
    ComponentTypeDef(id="service", category="SOFTWARE", name="Сервис", icon="service"),
    ComponentTypeDef(id="backend", category="SOFTWARE", name="Бэкенд", icon="server"),
    ComponentTypeDef(id="frontend", category="SOFTWARE", name="Фронтенд", icon="layout"),
    ComponentTypeDef(id="library", category="SOFTWARE", name="Библиотека", icon="book"),
    ComponentTypeDef(id="module", category="SOFTWARE", name="Модуль", icon="puzzle"),
    ComponentTypeDef(id="api", category="SOFTWARE", name="API", icon="api"),
    ComponentTypeDef(id="mcu", category="HARDWARE", name="MCU", icon="chip"),
    ComponentTypeDef(id="cpu", category="HARDWARE", name="CPU", icon="cpu"),
    ComponentTypeDef(id="sbc", category="HARDWARE", name="SBC", icon="board"),
    ComponentTypeDef(id="plc", category="HARDWARE", name="ПЛК", icon="factory"),
    ComponentTypeDef(id="limit-switch", category="HARDWARE", name="Концевой выключатель", icon="sensor"),
    ComponentTypeDef(id="hc-sr04", category="HARDWARE", name="Дальномер HC-SR04", icon="sensor"),
    ComponentTypeDef(id="vl53l0x", category="HARDWARE", name="Датчик расстояния VL53L0X", icon="sensor"),
    ComponentTypeDef(id="ds18b20", category="HARDWARE", name="Датчик температуры DS18B20", icon="sensor"),
    ComponentTypeDef(id="position-sensor", category="HARDWARE", name="Датчик положения", icon="sensor"),
    ComponentTypeDef(id="actuator", category="HARDWARE", name="Исполнитель", icon="motor"),
    ComponentTypeDef(id="motor-controller", category="HARDWARE", name="Контроллер двигателя", icon="motor"),
    ComponentTypeDef(id="camera", category="HARDWARE", name="Камера", icon="camera"),
    ComponentTypeDef(id="lidar", category="HARDWARE", name="LiDAR", icon="radar"),
    ComponentTypeDef(id="network-device", category="HARDWARE", name="Сетевое устройство", icon="network"),
    ComponentTypeDef(id="custom-hardware", category="HARDWARE", name="Своё железо", icon="box"),
    ComponentTypeDef(id="postgresql", category="DATA", name="PostgreSQL", icon="db"),
    ComponentTypeDef(id="mysql", category="DATA", name="MySQL", icon="db"),
    ComponentTypeDef(id="sqlite", category="DATA", name="SQLite", icon="db"),
    ComponentTypeDef(id="redis", category="DATA", name="Redis", icon="cache"),
    ComponentTypeDef(id="mongodb", category="DATA", name="MongoDB", icon="db"),
    ComponentTypeDef(id="file-storage", category="DATA", name="Файловое хранилище", icon="folder"),
    ComponentTypeDef(id="message-queue", category="DATA", name="Очередь сообщений", icon="queue"),
    ComponentTypeDef(id="custom-database", category="DATA", name="Своя БД", icon="db"),
    ComponentTypeDef(id="http", category="PROTOCOL", name="HTTP", icon="protocol"),
    ComponentTypeDef(id="https", category="PROTOCOL", name="HTTPS", icon="protocol"),
    ComponentTypeDef(id="tcp", category="PROTOCOL", name="TCP", icon="protocol"),
    ComponentTypeDef(id="udp", category="PROTOCOL", name="UDP", icon="protocol"),
    ComponentTypeDef(id="mqtt", category="PROTOCOL", name="MQTT", icon="protocol"),
    ComponentTypeDef(id="websocket", category="PROTOCOL", name="WebSocket", icon="protocol"),
    ComponentTypeDef(id="modbus-tcp", category="PROTOCOL", name="Modbus TCP", icon="protocol"),
    ComponentTypeDef(id="modbus-rtu", category="PROTOCOL", name="Modbus RTU", icon="protocol"),
    ComponentTypeDef(id="can", category="PROTOCOL", name="CAN", icon="protocol"),
    ComponentTypeDef(id="opc-ua", category="PROTOCOL", name="OPC UA", icon="protocol"),
    ComponentTypeDef(id="opc-da", category="PROTOCOL", name="OPC DA", icon="protocol"),
    ComponentTypeDef(id="serial", category="PROTOCOL", name="Serial", icon="protocol"),
    ComponentTypeDef(id="custom-protocol", category="PROTOCOL", name="Свой протокол", icon="protocol"),
    ComponentTypeDef(id="cloud", category="OTHER", name="Облако", icon="cloud"),
    ComponentTypeDef(id="external-service", category="OTHER", name="Внешний сервис", icon="globe"),
    ComponentTypeDef(id="user", category="OTHER", name="Пользователь", icon="user"),
    ComponentTypeDef(id="gateway", category="NETWORK", name="Шлюз", icon="network"),
    ComponentTypeDef(id="router", category="NETWORK", name="Маршрутизатор", icon="network"),
    ComponentTypeDef(id="switch", category="NETWORK", name="Коммутатор", icon="network"),
    ComponentTypeDef(id="mech-assembly", category="MECHANICS", name="Механический узел", icon="gear"),
    ComponentTypeDef(id="mech-part", category="MECHANICS", name="Деталь", icon="part"),
    ComponentTypeDef(id="mech-motor", category="MECHANICS", name="Двигатель", icon="motor"),
    ComponentTypeDef(id="mech-gearbox", category="MECHANICS", name="Редуктор", icon="gear"),
    ComponentTypeDef(id="mech-shaft", category="MECHANICS", name="Вал", icon="part"),
    ComponentTypeDef(id="mech-bearing", category="MECHANICS", name="Подшипник", icon="part"),
    ComponentTypeDef(id="mech-wheel", category="MECHANICS", name="Колесо", icon="part"),
    ComponentTypeDef(id="mech-bracket", category="MECHANICS", name="Кронштейн", icon="part"),
    ComponentTypeDef(id="mech-housing", category="MECHANICS", name="Корпус", icon="box"),
    ComponentTypeDef(id="table", category="DATA", name="Таблица", icon="db"),
    ComponentTypeDef(id="gpu", category="HARDWARE", name="GPU", icon="cpu"),
    ComponentTypeDef(id="ipc", category="HARDWARE", name="IPC", icon="cpu"),
    ComponentTypeDef(id="imu", category="HARDWARE", name="IMU", icon="sensor"),
    ComponentTypeDef(id="encoder", category="HARDWARE", name="Энкодер", icon="sensor"),
    ComponentTypeDef(id="servo", category="HARDWARE", name="Сервопривод", icon="motor"),
    ComponentTypeDef(id="drive", category="HARDWARE", name="Привод", icon="motor"),
    ComponentTypeDef(id="manipulator", category="HARDWARE", name="Манипулятор", icon="gear"),
    ComponentTypeDef(id="jetson", category="HARDWARE", name="Jetson", icon="board"),
    ComponentTypeDef(id="ethercat", category="PROTOCOL", name="EtherCAT", icon="protocol"),
    ComponentTypeDef(id="profinet", category="PROTOCOL", name="PROFINET", icon="protocol"),
    ComponentTypeDef(id="canopen", category="PROTOCOL", name="CANopen", icon="protocol"),
    ComponentTypeDef(id="ros2", category="PROTOCOL", name="ROS 2", icon="protocol"),
    ComponentTypeDef(id="dds", category="PROTOCOL", name="DDS", icon="protocol"),
    ComponentTypeDef(id="rest", category="PROTOCOL", name="REST", icon="protocol"),
    ComponentTypeDef(id="python", category="SOFTWARE", name="Python", icon="app"),
    ComponentTypeDef(id="cpp", category="SOFTWARE", name="C++", icon="app"),
    ComponentTypeDef(id="csharp", category="SOFTWARE", name="C#", icon="app"),
    ComponentTypeDef(id="ros2-sw", category="SOFTWARE", name="ROS 2 middleware", icon="puzzle"),
    ComponentTypeDef(id="linux", category="SOFTWARE", name="Linux", icon="app"),
    ComponentTypeDef(id="windows", category="SOFTWARE", name="Windows", icon="app"),
    ComponentTypeDef(id="fastapi", category="SOFTWARE", name="FastAPI", icon="server"),
    ComponentTypeDef(id="kafka", category="DATA", name="Kafka", icon="queue"),
    ComponentTypeDef(id="docker", category="SOFTWARE", name="Docker", icon="box"),
    ComponentTypeDef(id="tcpip", category="PROTOCOL", name="TCP/IP", icon="protocol"),
    ComponentTypeDef(id="java", category="SOFTWARE", name="Java", icon="app"),
    ComponentTypeDef(id="go", category="SOFTWARE", name="Go", icon="app"),
    ComponentTypeDef(id="javascript", category="SOFTWARE", name="JavaScript", icon="app"),
    ComponentTypeDef(id="typescript", category="SOFTWARE", name="TypeScript", icon="app"),
    ComponentTypeDef(id="motor-dc", category="HARDWARE", name="ДПТ", icon="motor"),
    ComponentTypeDef(id="motor-ac", category="HARDWARE", name="АД", icon="motor"),
    ComponentTypeDef(id="motor-sync", category="HARDWARE", name="СД", icon="motor"),
    ComponentTypeDef(id="motor-step", category="HARDWARE", name="Шаговый", icon="motor"),
    ComponentTypeDef(id="electrical", category="ELECTRICAL", name="Электрика", icon="power"),
    ComponentTypeDef(id="battery", category="ELECTRICAL", name="Аккумулятор", icon="power"),
    ComponentTypeDef(id="divider", category="ELECTRICAL", name="Делитель напряжения", icon="power"),
    ComponentTypeDef(id="psu", category="ELECTRICAL", name="Блок питания", icon="power"),
    ComponentTypeDef(id="electrical-link", category="PROTOCOL", name="Электрическое подключение", icon="protocol"),
]


BUILTIN_PROTOCOLS: list[Protocol] = [
    Protocol(id="proto-http", name="HTTP", version="1.1", transport="TCP", port="80", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="Протокол передачи гипертекста", built_in=True),
    Protocol(id="proto-https", name="HTTPS", version="1.1", transport="TCP/TLS", port="443", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="HTTP поверх TLS", built_in=True),
    Protocol(id="proto-tcp", name="TCP", version="1.0", transport="TCP", port="", direction="bidirectional", data_format="Binary", description="Протокол управления передачей", built_in=True),
    Protocol(id="proto-udp", name="UDP", version="1.0", transport="UDP", port="", direction="unidirectional", data_format="Binary", description="Протокол пользовательских датаграмм", built_in=True),
    Protocol(id="proto-mqtt", name="MQTT", version="5.0", transport="TCP", port="1883", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="Лёгкий протокол публикации и подписки", message_structure="topic + payload", timeout="30 с", retry="экспоненциальный backoff", built_in=True),
    Protocol(id="proto-ws", name="WebSocket", version="13", transport="TCP", port="80/443", direction="bidirectional", data_format="JSON", description="Двусторонний канал браузер/сервер", built_in=True),
    Protocol(id="proto-modbus-tcp", name="Modbus TCP", version="1.0", transport="TCP", port="502", direction="bidirectional", data_format="Registers", description="Промышленный Modbus поверх TCP", timeout="1 с", retry="3", crc="контрольная сумма TCP", built_in=True),
    Protocol(id="proto-modbus-rtu", name="Modbus RTU", version="1.0", transport="Serial", port="", direction="bidirectional", data_format="Registers", crc="CRC16", built_in=True),
    Protocol(id="proto-can", name="CAN", version="2.0", transport="CAN bus", port="", direction="bidirectional", data_format="Frames", description="Шина Controller Area Network", crc="CRC15", built_in=True),
    Protocol(id="proto-opcua", name="OPC UA", version="1.04", transport="TCP", port="4840", direction="bidirectional", data_format="Nodeset", built_in=True),
    Protocol(id="proto-opcda", name="OPC DA", version="3.0", transport="COM/DCOM", port="", direction="bidirectional", data_format="Items", built_in=True),
    Protocol(id="proto-serial", name="Serial", version="1.0", transport="UART", port="", direction="bidirectional", data_format="Bytes", encoding="ASCII", built_in=True, color="#4e6470"),
    Protocol(id="proto-uart", name="UART", version="1.0", transport="UART", direction="bidirectional", data_format="Bytes", built_in=True, color="#4e6470"),
    Protocol(id="proto-spi", name="SPI", version="1.0", transport="SPI", direction="bidirectional", data_format="Bytes", built_in=True, color="#5a5e6e"),
    Protocol(id="proto-i2c", name="I²C", version="1.0", transport="I2C", direction="bidirectional", data_format="Bytes", built_in=True, color="#4f6a66"),
    Protocol(id="proto-usb", name="USB", version="2.0", transport="USB", direction="bidirectional", built_in=True, color="#5c5870"),
    Protocol(id="proto-eth", name="Ethernet", version="1.0", transport="Ethernet", direction="bidirectional", built_in=True, color="#4a6270"),
    Protocol(id="proto-wifi", name="Wi-Fi", version="802.11", transport="Wi-Fi", direction="bidirectional", built_in=True, color="#4e5f78"),
    Protocol(id="proto-ethercat", name="EtherCAT", version="1.0", transport="Ethernet", port="", direction="bidirectional", data_format="Frames", description="Промышленный Ethernet реального времени", timing="цикл поля", built_in=True),
    Protocol(id="proto-profinet", name="PROFINET", version="2.4", transport="Ethernet", port="", direction="bidirectional", data_format="IO data", description="Промышленный Ethernet Siemens", built_in=True),
    Protocol(id="proto-canopen", name="CANopen", version="CiA 301", transport="CAN", direction="bidirectional", data_format="PDO/SDO", description="Протокол прикладного уровня над CAN", built_in=True),
    Protocol(id="proto-ros2", name="ROS 2", version="Humble+", transport="DDS", direction="bidirectional", data_format="Topics/Services", encoding="CDR", description="Middleware робототехнических узлов", built_in=True),
    Protocol(id="proto-dds", name="DDS", version="1.0", transport="UDP/TCP", direction="bidirectional", data_format="Topics", description="Data Distribution Service", built_in=True),
    Protocol(id="proto-rest", name="REST", version="HTTP", transport="TCP", port="443", direction="bidirectional", data_format="JSON", encoding="UTF-8", description="HTTP API в стиле REST", built_in=True),
    Protocol(id="proto-tcpip", name="TCP/IP", version="4/6", transport="IP", direction="bidirectional", data_format="Packets", description="Стек межсетевого обмена", built_in=True),
    Protocol(
        id="proto-electrical",
        name="Электрическое подключение",
        version="1.0",
        transport="провод",
        direction="unidirectional",
        data_format="электрический сигнал",
        description="Прямое проводное соединение без цифрового протокола: напряжение, ток, дискретный или ШИМ-сигнал.",
        message_structure="полярность, сечение, диапазон",
        built_in=True,
        color="#8a6a4a",
    ),
]

for _proto in BUILTIN_PROTOCOLS:
    if not _proto.color:
        _proto.color = color_for_protocol(_proto.name)


BUILTIN_HARDWARE: list[HardwareComponent] = [
    HardwareComponent(id="hw-stm32", name="STM32", manufacturer="STMicroelectronics", model="STM32F4", cpu="ARM Cortex-M4", ram="192KB", interfaces="UART, SPI, I2C, CAN, GPIO", voltage="3.3V", protocols="CAN, UART, Modbus", os="Bare-metal / FreeRTOS", category="MCU", built_in=True),
    HardwareComponent(id="hw-esp32", name="ESP32", manufacturer="Espressif", model="ESP32-WROOM", cpu="Xtensa LX6 dual-core", ram="520KB", interfaces="Wi-Fi, BLE, UART, SPI, I2C", voltage="3.3V", protocols="MQTT, HTTP, UART", os="ESP-IDF / Arduino", category="MCU", built_in=True),
    HardwareComponent(id="hw-rpi", name="Raspberry Pi", manufacturer="Raspberry Pi Ltd", model="Raspberry Pi 5", cpu="ARM Cortex-A76", ram="8GB", interfaces="Ethernet, USB, CSI, GPIO, HDMI", voltage="5V", protocols="HTTP, MQTT, WebSocket", os="Raspberry Pi OS", category="SBC", built_in=True),
    HardwareComponent(id="hw-arduino", name="Arduino", manufacturer="Arduino", model="Uno / Mega", cpu="ATmega328P", ram="2KB", interfaces="UART, SPI, I2C, GPIO", voltage="5V", protocols="Serial", os="Arduino", category="MCU", built_in=True),
    HardwareComponent(id="hw-siemens-plc", name="Siemens PLC", manufacturer="Siemens", model="S7-1500", cpu="ПЛК CPU", ram="", interfaces="PROFINET, Ethernet", voltage="24V", protocols="OPC UA, Modbus TCP, PROFINET", os="TIA Portal runtime", category="ПЛК", built_in=True),
    HardwareComponent(id="hw-ipc", name="Промышленный ПК", manufacturer="универсальный", model="IPC", cpu="x86_64", ram="16GB", interfaces="Ethernet, USB, PCIe", voltage="24V", protocols="OPC UA, MQTT, HTTP", os="Linux / Windows IoT", category="CPU", built_in=True),
    HardwareComponent(id="hw-sensor", name="Датчик", manufacturer="универсальный", model="", interfaces="I2C / Analog / UART", voltage="3.3V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-limit-switch", name="Концевой выключатель", manufacturer="универсальный", model="", interfaces="GPIO", voltage="3.3-24V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-hc-sr04", name="Дальномер HC-SR04", manufacturer="HC", model="HC-SR04", interfaces="GPIO Trigger/Echo", voltage="5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-vl53l0x", name="Датчик расстояния VL53L0X", manufacturer="STMicroelectronics", model="VL53L0X", interfaces="I2C", voltage="2.6-3.5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-ds18b20", name="Датчик температуры DS18B20", manufacturer="Maxim", model="DS18B20", interfaces="1-Wire", voltage="3.0-5.5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-position", name="Датчик положения", manufacturer="универсальный", model="", interfaces="Analog / SSI / I2C", voltage="3.3-5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-motor", name="Двигатель", manufacturer="универсальный", model="", interfaces="PWM / CAN", voltage="24V", category="ДПТ", built_in=True),
    HardwareComponent(id="hw-motor-ad", name="АД", manufacturer="универсальный", model="", interfaces="частотный преобразователь", voltage="230/400V AC", category="АД", built_in=True),
    HardwareComponent(id="hw-motor-sd", name="СД", manufacturer="универсальный", model="", interfaces="сервопривод / энкодер", voltage="24-400V", category="СД", built_in=True),
    HardwareComponent(id="hw-motor-step", name="Шаговый двигатель", manufacturer="универсальный", model="", interfaces="шаг/направление", voltage="12-48V", category="Шаговый", built_in=True),
    HardwareComponent(id="hw-battery", name="Аккумулятор", manufacturer="универсальный", model="", interfaces="DC", voltage="12-48V", category="Источник", built_in=True),
    HardwareComponent(id="hw-divider", name="Делитель напряжения", manufacturer="универсальный", model="", interfaces="аналог", voltage="", category="Электрика", built_in=True),
    HardwareComponent(id="hw-psu", name="Блок питания", manufacturer="универсальный", model="", interfaces="AC/DC", voltage="24V", category="Источник", built_in=True),
    HardwareComponent(id="hw-servo", name="Сервопривод", manufacturer="универсальный", model="", interfaces="PWM / RS485", voltage="24V", category="Исполнитель", built_in=True),
    HardwareComponent(id="hw-encoder", name="Энкодер", manufacturer="универсальный", model="", interfaces="A/B/Z / SSI", voltage="5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-camera", name="Камера", manufacturer="универсальный", model="", interfaces="CSI / USB / GigE", voltage="5V", protocols="RTSP / USB Video", category="Камера", built_in=True),
    HardwareComponent(id="hw-lidar", name="LiDAR", manufacturer="универсальный", model="", interfaces="Ethernet / UART", voltage="12V", protocols="UDP point cloud", category="LiDAR", built_in=True),
    HardwareComponent(id="hw-motor-ctrl", name="Контроллер двигателя", manufacturer="универсальный", model="", interfaces="CAN / PWM", voltage="24-48V", protocols="CAN", category="Контроллер двигателя", built_in=True),
    HardwareComponent(id="hw-gpu", name="GPU", manufacturer="универсальный", model="", interfaces="PCIe", voltage="", category="GPU", built_in=True),
    HardwareComponent(id="hw-imu", name="IMU", manufacturer="универсальный", model="", interfaces="SPI / I2C", voltage="3.3V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-jetson", name="Jetson", manufacturer="NVIDIA", model="Orin", cpu="ARM + GPU", ram="8-64GB", interfaces="CSI, USB, Ethernet, GPIO", voltage="9-20V", os="Linux", category="SBC", built_in=True),
    HardwareComponent(id="hw-ur", name="Манипулятор", manufacturer="универсальный", model="", interfaces="Ethernet / RTDE", voltage="48V", protocols="TCP, ROS 2", category="Манипулятор", built_in=True),
    HardwareComponent(id="hw-gnss", name="GNSS", manufacturer="универсальный", model="", interfaces="UART / USB", voltage="5V", category="Датчик", built_in=True),
    HardwareComponent(id="hw-hmi", name="HMI", manufacturer="универсальный", model="", interfaces="Ethernet / RS-485", voltage="24V", category="HMI", built_in=True),
    HardwareComponent(id="hw-relay", name="Реле", manufacturer="универсальный", model="", interfaces="сухой контакт", voltage="24V", category="Электрика", built_in=True),
    HardwareComponent(id="hw-fuse", name="Предохранитель", manufacturer="универсальный", model="", voltage="", category="Электрика", built_in=True),
    HardwareComponent(id="hw-terminal", name="Клеммник", manufacturer="универсальный", model="", voltage="", category="Электрика", built_in=True),
]


LIBRARY_PRESETS = [
    {"name": "PostgreSQL", "type": "PostgreSQL", "category": "DATA", "icon": "db", "technology": "PostgreSQL"},
    {"name": "MySQL", "type": "MySQL", "category": "DATA", "icon": "db", "technology": "MySQL"},
    {"name": "Redis", "type": "Redis", "category": "DATA", "icon": "cache", "technology": "Redis"},
    {"name": "Kafka", "type": "Kafka", "category": "DATA", "icon": "queue", "technology": "Kafka"},
    {"name": "MQTT", "type": "MQTT", "category": "PROTOCOL", "icon": "protocol", "technology": "MQTT", "protocol_id": "proto-mqtt"},
    {"name": "Ethernet", "type": "Ethernet", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-eth"},
    {"name": "TCP/IP", "type": "TCP/IP", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-tcpip"},
    {"name": "UDP", "type": "UDP", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-udp"},
    {"name": "HTTP / REST", "type": "REST", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-rest"},
    {"name": "WebSocket", "type": "WebSocket", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-ws"},
    {"name": "OPC UA", "type": "OPC UA", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-opcua"},
    {"name": "Modbus TCP", "type": "Modbus TCP", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-modbus-tcp"},
    {"name": "Modbus RTU", "type": "Modbus RTU", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-modbus-rtu"},
    {"name": "CAN", "type": "CAN", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-can"},
    {"name": "CANopen", "type": "CANopen", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-canopen"},
    {"name": "EtherCAT", "type": "EtherCAT", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-ethercat"},
    {"name": "PROFINET", "type": "PROFINET", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-profinet"},
    {"name": "ROS 2", "type": "ROS 2", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-ros2"},
    {"name": "Электрическое подключение", "type": "Электрическое подключение", "category": "PROTOCOL", "icon": "protocol", "protocol_id": "proto-electrical"},
    {"name": "Raspberry Pi", "type": "SBC", "category": "HARDWARE", "icon": "board", "technology": "Linux", "hardware_id": "hw-rpi"},
    {"name": "Jetson", "type": "SBC", "category": "HARDWARE", "icon": "board", "technology": "Linux", "hardware_id": "hw-jetson"},
    {"name": "STM32", "type": "MCU", "category": "HARDWARE", "icon": "chip", "technology": "C/C++", "hardware_id": "hw-stm32"},
    {"name": "ESP32", "type": "MCU", "category": "HARDWARE", "icon": "chip", "technology": "ESP-IDF", "hardware_id": "hw-esp32"},
    {"name": "Arduino", "type": "MCU", "category": "HARDWARE", "icon": "chip", "hardware_id": "hw-arduino"},
    {"name": "ПЛК", "type": "ПЛК", "category": "HARDWARE", "icon": "factory", "hardware_id": "hw-siemens-plc"},
    {"name": "IPC", "type": "IPC", "category": "HARDWARE", "icon": "cpu", "hardware_id": "hw-ipc"},
    {"name": "GPU", "type": "GPU", "category": "HARDWARE", "icon": "cpu", "hardware_id": "hw-gpu"},
    {"name": "Python", "type": "Python", "category": "SOFTWARE", "icon": "app", "technology": "Python"},
    {"name": "C++", "type": "C++", "category": "SOFTWARE", "icon": "app", "technology": "C++"},
    {"name": "C#", "type": "C#", "category": "SOFTWARE", "icon": "app", "technology": "C#"},
    {"name": "ROS 2 middleware", "type": "ROS 2 middleware", "category": "SOFTWARE", "icon": "puzzle", "technology": "ROS 2"},
    {"name": "FastAPI", "type": "FastAPI", "category": "SOFTWARE", "icon": "server", "technology": "Python"},
    {"name": "Python-бэкенд", "type": "Бэкенд", "category": "SOFTWARE", "icon": "server", "technology": "Python"},
    {"name": "React-фронтенд", "type": "Фронтенд", "category": "SOFTWARE", "icon": "layout", "technology": "React"},
    {"name": "Linux", "type": "Linux", "category": "SOFTWARE", "icon": "app", "technology": "Linux"},
    {"name": "Windows", "type": "Windows", "category": "SOFTWARE", "icon": "app", "technology": "Windows"},
    {"name": "Docker", "type": "Docker", "category": "SOFTWARE", "icon": "box", "technology": "Docker"},
    {"name": "Java", "type": "Java", "category": "SOFTWARE", "icon": "app", "technology": "Java"},
    {"name": "Go", "type": "Go", "category": "SOFTWARE", "icon": "app", "technology": "Go"},
    {"name": "JavaScript", "type": "JavaScript", "category": "SOFTWARE", "icon": "app", "technology": "JavaScript"},
    {"name": "TypeScript", "type": "TypeScript", "category": "SOFTWARE", "icon": "app", "technology": "TypeScript"},
    {"name": "SQLite", "type": "SQLite", "category": "DATA", "icon": "db", "technology": "SQLite"},
    {"name": "АД", "type": "АД", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor-ad"},
    {"name": "СД", "type": "СД", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor-sd"},
    {"name": "Шаговый двигатель", "type": "Шаговый", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor-step"},
    {"name": "Rust", "type": "Rust", "category": "SOFTWARE", "icon": "app", "technology": "Rust"},
    {"name": "Nginx", "type": "Nginx", "category": "SOFTWARE", "icon": "server", "technology": "Nginx"},
    {"name": "Node-RED", "type": "Node-RED", "category": "SOFTWARE", "icon": "puzzle", "technology": "Node-RED"},
    {"name": "Mosquitto", "type": "MQTT-брокер", "category": "SOFTWARE", "icon": "server", "technology": "MQTT"},
    {"name": "InfluxDB", "type": "InfluxDB", "category": "DATA", "icon": "db", "technology": "InfluxDB"},
    {"name": "Grafana", "type": "Grafana", "category": "SOFTWARE", "icon": "layout", "technology": "Grafana"},
    {"name": "GNSS", "type": "GNSS", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-gnss"},
    {"name": "HMI", "type": "HMI", "category": "HARDWARE", "icon": "layout", "hardware_id": "hw-hmi"},
    {"name": "Реле", "type": "Реле", "category": "ELECTRICAL", "icon": "relay", "hardware_id": "hw-relay"},
    {"name": "Предохранитель", "type": "Предохранитель", "category": "ELECTRICAL", "icon": "fuse", "hardware_id": "hw-fuse"},
    {"name": "Аккумулятор", "type": "Аккумулятор", "category": "ELECTRICAL", "icon": "flash", "hardware_id": "hw-battery"},
    {"name": "Делитель напряжения", "type": "Делитель напряжения", "category": "ELECTRICAL", "icon": "resistor", "hardware_id": "hw-divider"},
    {"name": "Блок питания", "type": "Блок питания", "category": "ELECTRICAL", "icon": "flash", "hardware_id": "hw-psu"},
    {"name": "Клеммник", "type": "Клеммник", "category": "ELECTRICAL", "icon": "connector", "hardware_id": "hw-terminal"},
    {"name": "Камера", "type": "Камера", "category": "HARDWARE", "icon": "camera", "hardware_id": "hw-camera"},
    {"name": "LiDAR", "type": "LiDAR", "category": "HARDWARE", "icon": "radar", "hardware_id": "hw-lidar"},
    {"name": "IMU", "type": "IMU", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-imu"},
    {"name": "Датчик", "type": "Датчик", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-sensor"},
    {"name": "Энкодер", "type": "Энкодер", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-encoder"},
    {"name": "Контроллер двигателя", "type": "Контроллер двигателя", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor-ctrl"},
    {"name": "Сервопривод", "type": "Сервопривод", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-servo"},
    {"name": "Двигатель", "type": "ДПТ", "category": "HARDWARE", "icon": "motor", "hardware_id": "hw-motor"},
    {"name": "Манипулятор", "type": "Манипулятор", "category": "HARDWARE", "icon": "gear", "hardware_id": "hw-ur"},
    {"name": "Концевой выключатель", "type": "Концевой выключатель", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-limit-switch"},
    {"name": "Дальномер HC-SR04", "type": "Дальномер HC-SR04", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-hc-sr04"},
    {"name": "Датчик расстояния VL53L0X", "type": "Датчик расстояния VL53L0X", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-vl53l0x"},
    {"name": "Датчик температуры DS18B20", "type": "Датчик температуры DS18B20", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-ds18b20"},
    {"name": "Датчик положения", "type": "Датчик положения", "category": "HARDWARE", "icon": "sensor", "hardware_id": "hw-position"},
    {"name": "Web-сервер", "type": "Web-сервер", "category": "SOFTWARE", "icon": "server", "technology": "HTTP"},
    {"name": "Шлюз", "type": "Шлюз", "category": "NETWORK", "icon": "network"},
    {"name": "Маршрутизатор", "type": "Маршрутизатор", "category": "NETWORK", "icon": "network"},
    {"name": "Коммутатор", "type": "Коммутатор", "category": "NETWORK", "icon": "network"},
    {"name": "Механическая система", "type": "Механический узел", "category": "MECHANICS", "icon": "gear"},
    {"name": "Колесо", "type": "Колесо", "category": "MECHANICS", "icon": "part"},
    {"name": "Редуктор", "type": "Редуктор", "category": "MECHANICS", "icon": "gear"},
    {"name": "Вал", "type": "Вал", "category": "MECHANICS", "icon": "part"},
    {"name": "Подшипник", "type": "Подшипник", "category": "MECHANICS", "icon": "part"},
    {"name": "Двигатель (мех.)", "type": "Двигатель", "category": "MECHANICS", "icon": "motor"},
    {"name": "Корпус", "type": "Корпус", "category": "MECHANICS", "icon": "box"},
    {"name": "Таблица", "type": "Таблица", "category": "DATA", "icon": "db", "entity_kind": "table"},
    {"name": "Трансформатор", "type": "Трансформатор", "category": "ELECTRICAL", "icon": "transformer"},
    {"name": "Лампа", "type": "Лампа", "category": "ELECTRICAL", "icon": "lamp"},
    {"name": "Диод", "type": "Диод", "category": "ELECTRICAL", "icon": "diode"},
    {"name": "Транзистор", "type": "Транзистор", "category": "ELECTRICAL", "icon": "transistor"},
    {"name": "Резистор", "type": "Резистор", "category": "ELECTRICAL", "icon": "resistor"},
    {"name": "Кнопка", "type": "Кнопка", "category": "ELECTRICAL", "icon": "button"},
    {"name": "Конденсатор", "type": "Конденсатор", "category": "ELECTRICAL", "icon": "capacitor"},
    {"name": "Катушка индуктивности", "type": "Катушка индуктивности", "category": "ELECTRICAL", "icon": "inductor"},
    {"name": "Переключатель", "type": "Переключатель", "category": "ELECTRICAL", "icon": "switch"},
    {"name": "Светодиод", "type": "Светодиод", "category": "ELECTRICAL", "icon": "led"},
    {"name": "Операционный усилитель", "type": "Операционный усилитель", "category": "ELECTRICAL", "icon": "opamp"},
    {"name": "Электрический разъём", "type": "Электрический разъём", "category": "ELECTRICAL", "icon": "connector"},
    {"name": "Автоматический выключатель", "type": "Автоматический выключатель", "category": "ELECTRICAL", "icon": "breaker"},
    {"name": "Kubernetes", "type": "Kubernetes", "category": "SOFTWARE", "icon": "box", "technology": "K8s"},
    {"name": "Prometheus", "type": "Prometheus", "category": "SOFTWARE", "icon": "layout", "technology": "Prometheus"},
    {"name": "FreeRTOS", "type": "FreeRTOS", "category": "SOFTWARE", "icon": "app", "technology": "C"},
    {"name": "Zephyr", "type": "Zephyr", "category": "SOFTWARE", "icon": "app", "technology": "C"},
    {"name": "gRPC", "type": "gRPC", "category": "SOFTWARE", "icon": "server", "technology": "gRPC"},
    {"name": "Protobuf", "type": "Protobuf", "category": "DATA", "icon": "box", "technology": "protobuf"},
    {"name": "TimescaleDB", "type": "TimescaleDB", "category": "DATA", "icon": "db", "technology": "PostgreSQL"},
    {"name": "ClickHouse", "type": "ClickHouse", "category": "DATA", "icon": "db", "technology": "ClickHouse"},
    {"name": "NATS", "type": "NATS", "category": "SOFTWARE", "icon": "queue", "technology": "NATS"},
    {"name": "LoRa", "type": "LoRa", "category": "NETWORK", "icon": "network", "technology": "LoRa"},
    {"name": "BLE", "type": "BLE", "category": "NETWORK", "icon": "network", "technology": "BLE"},
    {"name": "LTE-модем", "type": "LTE-модем", "category": "NETWORK", "icon": "network"},
    {"name": "EtherNet/IP", "type": "EtherNet/IP", "category": "NETWORK", "icon": "network", "technology": "CIP"},
    {"name": "OpenCV", "type": "OpenCV", "category": "SOFTWARE", "icon": "camera", "technology": "C++"},
    {"name": "Gazebo", "type": "Gazebo", "category": "SOFTWARE", "icon": "box", "technology": "ROS 2"},
]


def _with_preset_meta(items: list[dict]) -> list[dict]:
    colors = {
        "SOFTWARE": "#2F9E78",
        "HARDWARE": "#C46B2E",
        "DATA": "#2B8FD4",
        "PROTOCOL": "#6B5AD8",
        "NETWORK": "#155E75",
        "MECHANICS": "#A16207",
        "ELECTRICAL": "#D9773A",
        "OTHER": "#57534E",
    }
    out: list[dict] = []
    for i, item in enumerate(items):
        row = dict(item)
        slug = f"{row.get('category', 'x')}-{row.get('name', 'x')}-{i}".lower()
        slug = "".join(ch if ch.isalnum() else "-" for ch in slug)
        row.setdefault("id", f"lib-{slug}")
        row.setdefault("color", colors.get(str(row.get("category")), "#5c5a54"))
        row.setdefault("built_in", True)
        row.setdefault("technology", row.get("technology") or "")
        row.setdefault("entity_kind", row.get("entity_kind") or "component")
        out.append(row)
    return out


LIBRARY_PRESETS = _with_preset_meta(LIBRARY_PRESETS)
